/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutUsersRouteRouteImport } from './routes/_layout/users/route'
import { Route as LayoutCatalogRouteRouteImport } from './routes/_layout/catalog/route'
import { Route as LayoutUsersIndexRouteImport } from './routes/_layout/users/index'
import { Route as LayoutStudyPlansIndexRouteImport } from './routes/_layout/study-plans/index'
import { Route as LayoutCatalogIndexRouteImport } from './routes/_layout/catalog/index'
import { Route as LayoutUsersNewRouteImport } from './routes/_layout/users/new'
import { Route as LayoutStudyPlansNewRouteImport } from './routes/_layout/study-plans/new'
import { Route as LayoutStudyPlansStudyPlanIdRouteRouteImport } from './routes/_layout/study-plans/$studyPlanId/route'
import { Route as LayoutStudyPlansStudyPlanIdIndexRouteImport } from './routes/_layout/study-plans/$studyPlanId/index'
import { Route as LayoutCatalogProgramsIndexRouteImport } from './routes/_layout/catalog/programs/index'
import { Route as LayoutCatalogCoursesIndexRouteImport } from './routes/_layout/catalog/courses/index'
import { Route as LayoutStudyPlansStudyPlanIdProgramMapRouteImport } from './routes/_layout/study-plans/$studyPlanId/program-map'
import { Route as LayoutStudyPlansStudyPlanIdCoursesRouteImport } from './routes/_layout/study-plans/$studyPlanId/courses'
import { Route as LayoutCatalogProgramsNewRouteImport } from './routes/_layout/catalog/programs/new'
import { Route as LayoutCatalogCoursesNewRouteImport } from './routes/_layout/catalog/courses/new'
import { Route as LayoutCatalogProgramsProgramIdRouteRouteImport } from './routes/_layout/catalog/programs/$programId/route'
import { Route as LayoutCatalogCoursesCourseIdRouteRouteImport } from './routes/_layout/catalog/courses/$courseId/route'
import { Route as LayoutStudyPlansStudyPlanIdSectionsIndexRouteImport } from './routes/_layout/study-plans/$studyPlanId/sections/index'
import { Route as LayoutStudyPlansStudyPlanIdDetailsIndexRouteImport } from './routes/_layout/study-plans/$studyPlanId/details/index'
import { Route as LayoutCatalogProgramsProgramIdIndexRouteImport } from './routes/_layout/catalog/programs/$programId/index'
import { Route as LayoutCatalogCoursesCourseIdIndexRouteImport } from './routes/_layout/catalog/courses/$courseId/index'
import { Route as LayoutStudyPlansStudyPlanIdSectionsNewRouteImport } from './routes/_layout/study-plans/$studyPlanId/sections/new'
import { Route as LayoutStudyPlansStudyPlanIdDetailsEditRouteImport } from './routes/_layout/study-plans/$studyPlanId/details/edit'
import { Route as LayoutCatalogProgramsProgramIdEditRouteImport } from './routes/_layout/catalog/programs/$programId/edit'
import { Route as LayoutCatalogCoursesCourseIdEditRouteImport } from './routes/_layout/catalog/courses/$courseId/edit'
import { Route as LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRouteImport } from './routes/_layout/study-plans/$studyPlanId/sections/$sectionId/index'
import { Route as LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRouteImport } from './routes/_layout/study-plans/$studyPlanId/sections/$sectionId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutUsersRouteRoute = LayoutUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutCatalogRouteRoute = LayoutCatalogRouteRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutUsersIndexRoute = LayoutUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutUsersRouteRoute,
} as any)
const LayoutStudyPlansIndexRoute = LayoutStudyPlansIndexRouteImport.update({
  id: '/study-plans/',
  path: '/study-plans/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutCatalogIndexRoute = LayoutCatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutCatalogRouteRoute,
} as any)
const LayoutUsersNewRoute = LayoutUsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutUsersRouteRoute,
} as any)
const LayoutStudyPlansNewRoute = LayoutStudyPlansNewRouteImport.update({
  id: '/study-plans/new',
  path: '/study-plans/new',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutStudyPlansStudyPlanIdRouteRoute =
  LayoutStudyPlansStudyPlanIdRouteRouteImport.update({
    id: '/study-plans/$studyPlanId',
    path: '/study-plans/$studyPlanId',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutStudyPlansStudyPlanIdIndexRoute =
  LayoutStudyPlansStudyPlanIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)
const LayoutCatalogProgramsIndexRoute =
  LayoutCatalogProgramsIndexRouteImport.update({
    id: '/programs/',
    path: '/programs/',
    getParentRoute: () => LayoutCatalogRouteRoute,
  } as any)
const LayoutCatalogCoursesIndexRoute =
  LayoutCatalogCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => LayoutCatalogRouteRoute,
  } as any)
const LayoutStudyPlansStudyPlanIdProgramMapRoute =
  LayoutStudyPlansStudyPlanIdProgramMapRouteImport.update({
    id: '/program-map',
    path: '/program-map',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)
const LayoutStudyPlansStudyPlanIdCoursesRoute =
  LayoutStudyPlansStudyPlanIdCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)
const LayoutCatalogProgramsNewRoute =
  LayoutCatalogProgramsNewRouteImport.update({
    id: '/programs/new',
    path: '/programs/new',
    getParentRoute: () => LayoutCatalogRouteRoute,
  } as any)
const LayoutCatalogCoursesNewRoute = LayoutCatalogCoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => LayoutCatalogRouteRoute,
} as any)
const LayoutCatalogProgramsProgramIdRouteRoute =
  LayoutCatalogProgramsProgramIdRouteRouteImport.update({
    id: '/programs/$programId',
    path: '/programs/$programId',
    getParentRoute: () => LayoutCatalogRouteRoute,
  } as any)
const LayoutCatalogCoursesCourseIdRouteRoute =
  LayoutCatalogCoursesCourseIdRouteRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => LayoutCatalogRouteRoute,
  } as any)
const LayoutStudyPlansStudyPlanIdSectionsIndexRoute =
  LayoutStudyPlansStudyPlanIdSectionsIndexRouteImport.update({
    id: '/sections/',
    path: '/sections/',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)
const LayoutStudyPlansStudyPlanIdDetailsIndexRoute =
  LayoutStudyPlansStudyPlanIdDetailsIndexRouteImport.update({
    id: '/details/',
    path: '/details/',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)
const LayoutCatalogProgramsProgramIdIndexRoute =
  LayoutCatalogProgramsProgramIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutCatalogProgramsProgramIdRouteRoute,
  } as any)
const LayoutCatalogCoursesCourseIdIndexRoute =
  LayoutCatalogCoursesCourseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutCatalogCoursesCourseIdRouteRoute,
  } as any)
const LayoutStudyPlansStudyPlanIdSectionsNewRoute =
  LayoutStudyPlansStudyPlanIdSectionsNewRouteImport.update({
    id: '/sections/new',
    path: '/sections/new',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)
const LayoutStudyPlansStudyPlanIdDetailsEditRoute =
  LayoutStudyPlansStudyPlanIdDetailsEditRouteImport.update({
    id: '/details/edit',
    path: '/details/edit',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)
const LayoutCatalogProgramsProgramIdEditRoute =
  LayoutCatalogProgramsProgramIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => LayoutCatalogProgramsProgramIdRouteRoute,
  } as any)
const LayoutCatalogCoursesCourseIdEditRoute =
  LayoutCatalogCoursesCourseIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => LayoutCatalogCoursesCourseIdRouteRoute,
  } as any)
const LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRoute =
  LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRouteImport.update({
    id: '/sections/$sectionId/',
    path: '/sections/$sectionId/',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)
const LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRoute =
  LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRouteImport.update({
    id: '/sections/$sectionId/edit',
    path: '/sections/$sectionId/edit',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/catalog': typeof LayoutCatalogRouteRouteWithChildren
  '/users': typeof LayoutUsersRouteRouteWithChildren
  '/study-plans/$studyPlanId': typeof LayoutStudyPlansStudyPlanIdRouteRouteWithChildren
  '/study-plans/new': typeof LayoutStudyPlansNewRoute
  '/users/new': typeof LayoutUsersNewRoute
  '/catalog/': typeof LayoutCatalogIndexRoute
  '/study-plans': typeof LayoutStudyPlansIndexRoute
  '/users/': typeof LayoutUsersIndexRoute
  '/catalog/courses/$courseId': typeof LayoutCatalogCoursesCourseIdRouteRouteWithChildren
  '/catalog/programs/$programId': typeof LayoutCatalogProgramsProgramIdRouteRouteWithChildren
  '/catalog/courses/new': typeof LayoutCatalogCoursesNewRoute
  '/catalog/programs/new': typeof LayoutCatalogProgramsNewRoute
  '/study-plans/$studyPlanId/courses': typeof LayoutStudyPlansStudyPlanIdCoursesRoute
  '/study-plans/$studyPlanId/program-map': typeof LayoutStudyPlansStudyPlanIdProgramMapRoute
  '/catalog/courses': typeof LayoutCatalogCoursesIndexRoute
  '/catalog/programs': typeof LayoutCatalogProgramsIndexRoute
  '/study-plans/$studyPlanId/': typeof LayoutStudyPlansStudyPlanIdIndexRoute
  '/catalog/courses/$courseId/edit': typeof LayoutCatalogCoursesCourseIdEditRoute
  '/catalog/programs/$programId/edit': typeof LayoutCatalogProgramsProgramIdEditRoute
  '/study-plans/$studyPlanId/details/edit': typeof LayoutStudyPlansStudyPlanIdDetailsEditRoute
  '/study-plans/$studyPlanId/sections/new': typeof LayoutStudyPlansStudyPlanIdSectionsNewRoute
  '/catalog/courses/$courseId/': typeof LayoutCatalogCoursesCourseIdIndexRoute
  '/catalog/programs/$programId/': typeof LayoutCatalogProgramsProgramIdIndexRoute
  '/study-plans/$studyPlanId/details': typeof LayoutStudyPlansStudyPlanIdDetailsIndexRoute
  '/study-plans/$studyPlanId/sections': typeof LayoutStudyPlansStudyPlanIdSectionsIndexRoute
  '/study-plans/$studyPlanId/sections/$sectionId/edit': typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRoute
  '/study-plans/$studyPlanId/sections/$sectionId': typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/study-plans/new': typeof LayoutStudyPlansNewRoute
  '/users/new': typeof LayoutUsersNewRoute
  '/catalog': typeof LayoutCatalogIndexRoute
  '/study-plans': typeof LayoutStudyPlansIndexRoute
  '/users': typeof LayoutUsersIndexRoute
  '/catalog/courses/new': typeof LayoutCatalogCoursesNewRoute
  '/catalog/programs/new': typeof LayoutCatalogProgramsNewRoute
  '/study-plans/$studyPlanId/courses': typeof LayoutStudyPlansStudyPlanIdCoursesRoute
  '/study-plans/$studyPlanId/program-map': typeof LayoutStudyPlansStudyPlanIdProgramMapRoute
  '/catalog/courses': typeof LayoutCatalogCoursesIndexRoute
  '/catalog/programs': typeof LayoutCatalogProgramsIndexRoute
  '/study-plans/$studyPlanId': typeof LayoutStudyPlansStudyPlanIdIndexRoute
  '/catalog/courses/$courseId/edit': typeof LayoutCatalogCoursesCourseIdEditRoute
  '/catalog/programs/$programId/edit': typeof LayoutCatalogProgramsProgramIdEditRoute
  '/study-plans/$studyPlanId/details/edit': typeof LayoutStudyPlansStudyPlanIdDetailsEditRoute
  '/study-plans/$studyPlanId/sections/new': typeof LayoutStudyPlansStudyPlanIdSectionsNewRoute
  '/catalog/courses/$courseId': typeof LayoutCatalogCoursesCourseIdIndexRoute
  '/catalog/programs/$programId': typeof LayoutCatalogProgramsProgramIdIndexRoute
  '/study-plans/$studyPlanId/details': typeof LayoutStudyPlansStudyPlanIdDetailsIndexRoute
  '/study-plans/$studyPlanId/sections': typeof LayoutStudyPlansStudyPlanIdSectionsIndexRoute
  '/study-plans/$studyPlanId/sections/$sectionId/edit': typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRoute
  '/study-plans/$studyPlanId/sections/$sectionId': typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/catalog': typeof LayoutCatalogRouteRouteWithChildren
  '/_layout/users': typeof LayoutUsersRouteRouteWithChildren
  '/_layout/study-plans/$studyPlanId': typeof LayoutStudyPlansStudyPlanIdRouteRouteWithChildren
  '/_layout/study-plans/new': typeof LayoutStudyPlansNewRoute
  '/_layout/users/new': typeof LayoutUsersNewRoute
  '/_layout/catalog/': typeof LayoutCatalogIndexRoute
  '/_layout/study-plans/': typeof LayoutStudyPlansIndexRoute
  '/_layout/users/': typeof LayoutUsersIndexRoute
  '/_layout/catalog/courses/$courseId': typeof LayoutCatalogCoursesCourseIdRouteRouteWithChildren
  '/_layout/catalog/programs/$programId': typeof LayoutCatalogProgramsProgramIdRouteRouteWithChildren
  '/_layout/catalog/courses/new': typeof LayoutCatalogCoursesNewRoute
  '/_layout/catalog/programs/new': typeof LayoutCatalogProgramsNewRoute
  '/_layout/study-plans/$studyPlanId/courses': typeof LayoutStudyPlansStudyPlanIdCoursesRoute
  '/_layout/study-plans/$studyPlanId/program-map': typeof LayoutStudyPlansStudyPlanIdProgramMapRoute
  '/_layout/catalog/courses/': typeof LayoutCatalogCoursesIndexRoute
  '/_layout/catalog/programs/': typeof LayoutCatalogProgramsIndexRoute
  '/_layout/study-plans/$studyPlanId/': typeof LayoutStudyPlansStudyPlanIdIndexRoute
  '/_layout/catalog/courses/$courseId/edit': typeof LayoutCatalogCoursesCourseIdEditRoute
  '/_layout/catalog/programs/$programId/edit': typeof LayoutCatalogProgramsProgramIdEditRoute
  '/_layout/study-plans/$studyPlanId/details/edit': typeof LayoutStudyPlansStudyPlanIdDetailsEditRoute
  '/_layout/study-plans/$studyPlanId/sections/new': typeof LayoutStudyPlansStudyPlanIdSectionsNewRoute
  '/_layout/catalog/courses/$courseId/': typeof LayoutCatalogCoursesCourseIdIndexRoute
  '/_layout/catalog/programs/$programId/': typeof LayoutCatalogProgramsProgramIdIndexRoute
  '/_layout/study-plans/$studyPlanId/details/': typeof LayoutStudyPlansStudyPlanIdDetailsIndexRoute
  '/_layout/study-plans/$studyPlanId/sections/': typeof LayoutStudyPlansStudyPlanIdSectionsIndexRoute
  '/_layout/study-plans/$studyPlanId/sections/$sectionId/edit': typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRoute
  '/_layout/study-plans/$studyPlanId/sections/$sectionId/': typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/catalog'
    | '/users'
    | '/study-plans/$studyPlanId'
    | '/study-plans/new'
    | '/users/new'
    | '/catalog/'
    | '/study-plans'
    | '/users/'
    | '/catalog/courses/$courseId'
    | '/catalog/programs/$programId'
    | '/catalog/courses/new'
    | '/catalog/programs/new'
    | '/study-plans/$studyPlanId/courses'
    | '/study-plans/$studyPlanId/program-map'
    | '/catalog/courses'
    | '/catalog/programs'
    | '/study-plans/$studyPlanId/'
    | '/catalog/courses/$courseId/edit'
    | '/catalog/programs/$programId/edit'
    | '/study-plans/$studyPlanId/details/edit'
    | '/study-plans/$studyPlanId/sections/new'
    | '/catalog/courses/$courseId/'
    | '/catalog/programs/$programId/'
    | '/study-plans/$studyPlanId/details'
    | '/study-plans/$studyPlanId/sections'
    | '/study-plans/$studyPlanId/sections/$sectionId/edit'
    | '/study-plans/$studyPlanId/sections/$sectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/study-plans/new'
    | '/users/new'
    | '/catalog'
    | '/study-plans'
    | '/users'
    | '/catalog/courses/new'
    | '/catalog/programs/new'
    | '/study-plans/$studyPlanId/courses'
    | '/study-plans/$studyPlanId/program-map'
    | '/catalog/courses'
    | '/catalog/programs'
    | '/study-plans/$studyPlanId'
    | '/catalog/courses/$courseId/edit'
    | '/catalog/programs/$programId/edit'
    | '/study-plans/$studyPlanId/details/edit'
    | '/study-plans/$studyPlanId/sections/new'
    | '/catalog/courses/$courseId'
    | '/catalog/programs/$programId'
    | '/study-plans/$studyPlanId/details'
    | '/study-plans/$studyPlanId/sections'
    | '/study-plans/$studyPlanId/sections/$sectionId/edit'
    | '/study-plans/$studyPlanId/sections/$sectionId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/_layout/catalog'
    | '/_layout/users'
    | '/_layout/study-plans/$studyPlanId'
    | '/_layout/study-plans/new'
    | '/_layout/users/new'
    | '/_layout/catalog/'
    | '/_layout/study-plans/'
    | '/_layout/users/'
    | '/_layout/catalog/courses/$courseId'
    | '/_layout/catalog/programs/$programId'
    | '/_layout/catalog/courses/new'
    | '/_layout/catalog/programs/new'
    | '/_layout/study-plans/$studyPlanId/courses'
    | '/_layout/study-plans/$studyPlanId/program-map'
    | '/_layout/catalog/courses/'
    | '/_layout/catalog/programs/'
    | '/_layout/study-plans/$studyPlanId/'
    | '/_layout/catalog/courses/$courseId/edit'
    | '/_layout/catalog/programs/$programId/edit'
    | '/_layout/study-plans/$studyPlanId/details/edit'
    | '/_layout/study-plans/$studyPlanId/sections/new'
    | '/_layout/catalog/courses/$courseId/'
    | '/_layout/catalog/programs/$programId/'
    | '/_layout/study-plans/$studyPlanId/details/'
    | '/_layout/study-plans/$studyPlanId/sections/'
    | '/_layout/study-plans/$studyPlanId/sections/$sectionId/edit'
    | '/_layout/study-plans/$studyPlanId/sections/$sectionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/users': {
      id: '/_layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersRouteRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/catalog': {
      id: '/_layout/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof LayoutCatalogRouteRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/users/': {
      id: '/_layout/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof LayoutUsersIndexRouteImport
      parentRoute: typeof LayoutUsersRouteRoute
    }
    '/_layout/study-plans/': {
      id: '/_layout/study-plans/'
      path: '/study-plans'
      fullPath: '/study-plans'
      preLoaderRoute: typeof LayoutStudyPlansIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/catalog/': {
      id: '/_layout/catalog/'
      path: '/'
      fullPath: '/catalog/'
      preLoaderRoute: typeof LayoutCatalogIndexRouteImport
      parentRoute: typeof LayoutCatalogRouteRoute
    }
    '/_layout/users/new': {
      id: '/_layout/users/new'
      path: '/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof LayoutUsersNewRouteImport
      parentRoute: typeof LayoutUsersRouteRoute
    }
    '/_layout/study-plans/new': {
      id: '/_layout/study-plans/new'
      path: '/study-plans/new'
      fullPath: '/study-plans/new'
      preLoaderRoute: typeof LayoutStudyPlansNewRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/study-plans/$studyPlanId': {
      id: '/_layout/study-plans/$studyPlanId'
      path: '/study-plans/$studyPlanId'
      fullPath: '/study-plans/$studyPlanId'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdRouteRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/study-plans/$studyPlanId/': {
      id: '/_layout/study-plans/$studyPlanId/'
      path: '/'
      fullPath: '/study-plans/$studyPlanId/'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdIndexRouteImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteRoute
    }
    '/_layout/catalog/programs/': {
      id: '/_layout/catalog/programs/'
      path: '/programs'
      fullPath: '/catalog/programs'
      preLoaderRoute: typeof LayoutCatalogProgramsIndexRouteImport
      parentRoute: typeof LayoutCatalogRouteRoute
    }
    '/_layout/catalog/courses/': {
      id: '/_layout/catalog/courses/'
      path: '/courses'
      fullPath: '/catalog/courses'
      preLoaderRoute: typeof LayoutCatalogCoursesIndexRouteImport
      parentRoute: typeof LayoutCatalogRouteRoute
    }
    '/_layout/study-plans/$studyPlanId/program-map': {
      id: '/_layout/study-plans/$studyPlanId/program-map'
      path: '/program-map'
      fullPath: '/study-plans/$studyPlanId/program-map'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdProgramMapRouteImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteRoute
    }
    '/_layout/study-plans/$studyPlanId/courses': {
      id: '/_layout/study-plans/$studyPlanId/courses'
      path: '/courses'
      fullPath: '/study-plans/$studyPlanId/courses'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdCoursesRouteImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteRoute
    }
    '/_layout/catalog/programs/new': {
      id: '/_layout/catalog/programs/new'
      path: '/programs/new'
      fullPath: '/catalog/programs/new'
      preLoaderRoute: typeof LayoutCatalogProgramsNewRouteImport
      parentRoute: typeof LayoutCatalogRouteRoute
    }
    '/_layout/catalog/courses/new': {
      id: '/_layout/catalog/courses/new'
      path: '/courses/new'
      fullPath: '/catalog/courses/new'
      preLoaderRoute: typeof LayoutCatalogCoursesNewRouteImport
      parentRoute: typeof LayoutCatalogRouteRoute
    }
    '/_layout/catalog/programs/$programId': {
      id: '/_layout/catalog/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/catalog/programs/$programId'
      preLoaderRoute: typeof LayoutCatalogProgramsProgramIdRouteRouteImport
      parentRoute: typeof LayoutCatalogRouteRoute
    }
    '/_layout/catalog/courses/$courseId': {
      id: '/_layout/catalog/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/catalog/courses/$courseId'
      preLoaderRoute: typeof LayoutCatalogCoursesCourseIdRouteRouteImport
      parentRoute: typeof LayoutCatalogRouteRoute
    }
    '/_layout/study-plans/$studyPlanId/sections/': {
      id: '/_layout/study-plans/$studyPlanId/sections/'
      path: '/sections'
      fullPath: '/study-plans/$studyPlanId/sections'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdSectionsIndexRouteImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteRoute
    }
    '/_layout/study-plans/$studyPlanId/details/': {
      id: '/_layout/study-plans/$studyPlanId/details/'
      path: '/details'
      fullPath: '/study-plans/$studyPlanId/details'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdDetailsIndexRouteImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteRoute
    }
    '/_layout/catalog/programs/$programId/': {
      id: '/_layout/catalog/programs/$programId/'
      path: '/'
      fullPath: '/catalog/programs/$programId/'
      preLoaderRoute: typeof LayoutCatalogProgramsProgramIdIndexRouteImport
      parentRoute: typeof LayoutCatalogProgramsProgramIdRouteRoute
    }
    '/_layout/catalog/courses/$courseId/': {
      id: '/_layout/catalog/courses/$courseId/'
      path: '/'
      fullPath: '/catalog/courses/$courseId/'
      preLoaderRoute: typeof LayoutCatalogCoursesCourseIdIndexRouteImport
      parentRoute: typeof LayoutCatalogCoursesCourseIdRouteRoute
    }
    '/_layout/study-plans/$studyPlanId/sections/new': {
      id: '/_layout/study-plans/$studyPlanId/sections/new'
      path: '/sections/new'
      fullPath: '/study-plans/$studyPlanId/sections/new'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdSectionsNewRouteImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteRoute
    }
    '/_layout/study-plans/$studyPlanId/details/edit': {
      id: '/_layout/study-plans/$studyPlanId/details/edit'
      path: '/details/edit'
      fullPath: '/study-plans/$studyPlanId/details/edit'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdDetailsEditRouteImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteRoute
    }
    '/_layout/catalog/programs/$programId/edit': {
      id: '/_layout/catalog/programs/$programId/edit'
      path: '/edit'
      fullPath: '/catalog/programs/$programId/edit'
      preLoaderRoute: typeof LayoutCatalogProgramsProgramIdEditRouteImport
      parentRoute: typeof LayoutCatalogProgramsProgramIdRouteRoute
    }
    '/_layout/catalog/courses/$courseId/edit': {
      id: '/_layout/catalog/courses/$courseId/edit'
      path: '/edit'
      fullPath: '/catalog/courses/$courseId/edit'
      preLoaderRoute: typeof LayoutCatalogCoursesCourseIdEditRouteImport
      parentRoute: typeof LayoutCatalogCoursesCourseIdRouteRoute
    }
    '/_layout/study-plans/$studyPlanId/sections/$sectionId/': {
      id: '/_layout/study-plans/$studyPlanId/sections/$sectionId/'
      path: '/sections/$sectionId'
      fullPath: '/study-plans/$studyPlanId/sections/$sectionId'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRouteImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteRoute
    }
    '/_layout/study-plans/$studyPlanId/sections/$sectionId/edit': {
      id: '/_layout/study-plans/$studyPlanId/sections/$sectionId/edit'
      path: '/sections/$sectionId/edit'
      fullPath: '/study-plans/$studyPlanId/sections/$sectionId/edit'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRouteImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteRoute
    }
  }
}

interface LayoutCatalogCoursesCourseIdRouteRouteChildren {
  LayoutCatalogCoursesCourseIdEditRoute: typeof LayoutCatalogCoursesCourseIdEditRoute
  LayoutCatalogCoursesCourseIdIndexRoute: typeof LayoutCatalogCoursesCourseIdIndexRoute
}

const LayoutCatalogCoursesCourseIdRouteRouteChildren: LayoutCatalogCoursesCourseIdRouteRouteChildren =
  {
    LayoutCatalogCoursesCourseIdEditRoute:
      LayoutCatalogCoursesCourseIdEditRoute,
    LayoutCatalogCoursesCourseIdIndexRoute:
      LayoutCatalogCoursesCourseIdIndexRoute,
  }

const LayoutCatalogCoursesCourseIdRouteRouteWithChildren =
  LayoutCatalogCoursesCourseIdRouteRoute._addFileChildren(
    LayoutCatalogCoursesCourseIdRouteRouteChildren,
  )

interface LayoutCatalogProgramsProgramIdRouteRouteChildren {
  LayoutCatalogProgramsProgramIdEditRoute: typeof LayoutCatalogProgramsProgramIdEditRoute
  LayoutCatalogProgramsProgramIdIndexRoute: typeof LayoutCatalogProgramsProgramIdIndexRoute
}

const LayoutCatalogProgramsProgramIdRouteRouteChildren: LayoutCatalogProgramsProgramIdRouteRouteChildren =
  {
    LayoutCatalogProgramsProgramIdEditRoute:
      LayoutCatalogProgramsProgramIdEditRoute,
    LayoutCatalogProgramsProgramIdIndexRoute:
      LayoutCatalogProgramsProgramIdIndexRoute,
  }

const LayoutCatalogProgramsProgramIdRouteRouteWithChildren =
  LayoutCatalogProgramsProgramIdRouteRoute._addFileChildren(
    LayoutCatalogProgramsProgramIdRouteRouteChildren,
  )

interface LayoutCatalogRouteRouteChildren {
  LayoutCatalogIndexRoute: typeof LayoutCatalogIndexRoute
  LayoutCatalogCoursesCourseIdRouteRoute: typeof LayoutCatalogCoursesCourseIdRouteRouteWithChildren
  LayoutCatalogProgramsProgramIdRouteRoute: typeof LayoutCatalogProgramsProgramIdRouteRouteWithChildren
  LayoutCatalogCoursesNewRoute: typeof LayoutCatalogCoursesNewRoute
  LayoutCatalogProgramsNewRoute: typeof LayoutCatalogProgramsNewRoute
  LayoutCatalogCoursesIndexRoute: typeof LayoutCatalogCoursesIndexRoute
  LayoutCatalogProgramsIndexRoute: typeof LayoutCatalogProgramsIndexRoute
}

const LayoutCatalogRouteRouteChildren: LayoutCatalogRouteRouteChildren = {
  LayoutCatalogIndexRoute: LayoutCatalogIndexRoute,
  LayoutCatalogCoursesCourseIdRouteRoute:
    LayoutCatalogCoursesCourseIdRouteRouteWithChildren,
  LayoutCatalogProgramsProgramIdRouteRoute:
    LayoutCatalogProgramsProgramIdRouteRouteWithChildren,
  LayoutCatalogCoursesNewRoute: LayoutCatalogCoursesNewRoute,
  LayoutCatalogProgramsNewRoute: LayoutCatalogProgramsNewRoute,
  LayoutCatalogCoursesIndexRoute: LayoutCatalogCoursesIndexRoute,
  LayoutCatalogProgramsIndexRoute: LayoutCatalogProgramsIndexRoute,
}

const LayoutCatalogRouteRouteWithChildren =
  LayoutCatalogRouteRoute._addFileChildren(LayoutCatalogRouteRouteChildren)

interface LayoutUsersRouteRouteChildren {
  LayoutUsersNewRoute: typeof LayoutUsersNewRoute
  LayoutUsersIndexRoute: typeof LayoutUsersIndexRoute
}

const LayoutUsersRouteRouteChildren: LayoutUsersRouteRouteChildren = {
  LayoutUsersNewRoute: LayoutUsersNewRoute,
  LayoutUsersIndexRoute: LayoutUsersIndexRoute,
}

const LayoutUsersRouteRouteWithChildren =
  LayoutUsersRouteRoute._addFileChildren(LayoutUsersRouteRouteChildren)

interface LayoutStudyPlansStudyPlanIdRouteRouteChildren {
  LayoutStudyPlansStudyPlanIdCoursesRoute: typeof LayoutStudyPlansStudyPlanIdCoursesRoute
  LayoutStudyPlansStudyPlanIdProgramMapRoute: typeof LayoutStudyPlansStudyPlanIdProgramMapRoute
  LayoutStudyPlansStudyPlanIdIndexRoute: typeof LayoutStudyPlansStudyPlanIdIndexRoute
  LayoutStudyPlansStudyPlanIdDetailsEditRoute: typeof LayoutStudyPlansStudyPlanIdDetailsEditRoute
  LayoutStudyPlansStudyPlanIdSectionsNewRoute: typeof LayoutStudyPlansStudyPlanIdSectionsNewRoute
  LayoutStudyPlansStudyPlanIdDetailsIndexRoute: typeof LayoutStudyPlansStudyPlanIdDetailsIndexRoute
  LayoutStudyPlansStudyPlanIdSectionsIndexRoute: typeof LayoutStudyPlansStudyPlanIdSectionsIndexRoute
  LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRoute: typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRoute
  LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRoute: typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRoute
}

const LayoutStudyPlansStudyPlanIdRouteRouteChildren: LayoutStudyPlansStudyPlanIdRouteRouteChildren =
  {
    LayoutStudyPlansStudyPlanIdCoursesRoute:
      LayoutStudyPlansStudyPlanIdCoursesRoute,
    LayoutStudyPlansStudyPlanIdProgramMapRoute:
      LayoutStudyPlansStudyPlanIdProgramMapRoute,
    LayoutStudyPlansStudyPlanIdIndexRoute:
      LayoutStudyPlansStudyPlanIdIndexRoute,
    LayoutStudyPlansStudyPlanIdDetailsEditRoute:
      LayoutStudyPlansStudyPlanIdDetailsEditRoute,
    LayoutStudyPlansStudyPlanIdSectionsNewRoute:
      LayoutStudyPlansStudyPlanIdSectionsNewRoute,
    LayoutStudyPlansStudyPlanIdDetailsIndexRoute:
      LayoutStudyPlansStudyPlanIdDetailsIndexRoute,
    LayoutStudyPlansStudyPlanIdSectionsIndexRoute:
      LayoutStudyPlansStudyPlanIdSectionsIndexRoute,
    LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRoute:
      LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRoute,
    LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRoute:
      LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRoute,
  }

const LayoutStudyPlansStudyPlanIdRouteRouteWithChildren =
  LayoutStudyPlansStudyPlanIdRouteRoute._addFileChildren(
    LayoutStudyPlansStudyPlanIdRouteRouteChildren,
  )

interface LayoutRouteRouteChildren {
  LayoutCatalogRouteRoute: typeof LayoutCatalogRouteRouteWithChildren
  LayoutUsersRouteRoute: typeof LayoutUsersRouteRouteWithChildren
  LayoutStudyPlansStudyPlanIdRouteRoute: typeof LayoutStudyPlansStudyPlanIdRouteRouteWithChildren
  LayoutStudyPlansNewRoute: typeof LayoutStudyPlansNewRoute
  LayoutStudyPlansIndexRoute: typeof LayoutStudyPlansIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutCatalogRouteRoute: LayoutCatalogRouteRouteWithChildren,
  LayoutUsersRouteRoute: LayoutUsersRouteRouteWithChildren,
  LayoutStudyPlansStudyPlanIdRouteRoute:
    LayoutStudyPlansStudyPlanIdRouteRouteWithChildren,
  LayoutStudyPlansNewRoute: LayoutStudyPlansNewRoute,
  LayoutStudyPlansIndexRoute: LayoutStudyPlansIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
