spring:
  config:
    activate:
      on-profile: dev
    import: file:../../dev.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
logging:
  level:
    org:
      springframework: DEBUG