spring:
  application:
    name: gjuplans
  sql:
    init:
      mode: always
  flyway:
    clean-disabled: true

jwt:
  cookieExpiry: ${JWT_COOKIEEXPIRY}

backend:
  api:
    key: ${BACKEND_API_KEY}