spring:
  config:
    import: file:../../dev.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

backend:
  api:
    key: ${BACKEND_API_KEY}