spring:
  application:
    name: gjuplans
  datasource:
    url: jdbc:postgresql://database:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    clean-disabled: true
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

jwt:
  cookie:
    expiry: 1800

server:
  forward-headers-strategy: native

backend:
  api:
    key: ${BACKEND_API_KEY}
