spring:
  application:
    name: gjuplans
  datasource:
    url: jdbc:postgresql://database:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

jwt:
  cookieExpiry: ${JWT_COOKIEEXPIRY:1800} # default 1800 seconds if not set

backend:
  api:
    key: ${BACKEND_API_KEY}

