spring:
  config:
    activate:
      on-profile: staging
  flyway:
    locations: "classpath:db/migration,classpath:dev/db/migration"

jwt:
  cookie:
    secure: true

cors:
  allowed-origins: https://admin-staging.gjuplans.com

server:
  port: 8081

logging:
  level:
    org:
      springframework: DEBUG