spring:
  config:
    activate:
      on-profile: prod

server:
  servlet:
    session:
      cookie:
        secure: true
  forward-headers-strategy: native

jwt:
  cookieSecure: true

logging:
  level:
    root: WARN