spring:
  application:
    name: gjuplans
  datasource:
    url: jdbc:postgresql://database/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    clean-disabled: true
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  cookie:
    expiry: 1800

server:
  forward-headers-strategy: native

backend:
  api:
    key: ${BACKEND_API_KEY}
