spring:
  config:
    activate:
      on-profile: dev
    import: file:../../dev.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}

logging:
  level:
    org:
      springframework: DEBUG