spring:
  config:
    activate:
      on-profile: staging

jwt:
  cookie:
    secure: true

cors:
  allowed-origins: https://admin-staging.gjuplans.com

server:
  port: 8081

logging:
  level:
    org:
      springframework: DEBUG