spring:
  application:
    name: gjuplans
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    clean-disabled: true
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

jwt:
  cookieExpiry: ${JWT_COOKIEEXPIRY}

backend:
  api:
    key: ${BACKEND_API_KEY}
