spring:
  config:
    activate:
      on-profile: dev
  flyway:
    locations: "classpath:db/migration,classpath:dev/db/migration"

server:
  servlet:
    session:
      cookie:
        secure: false

jwt:
  cookieSecure: false

logging:
  level:
    org:
      springframework: DEBUG