spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://not-localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

logging:
  level:
    root: WARN