spring:
  config:
    activate:
      on-profile: staging
  flyway:
    locations: "classpath:db/migration,classpath:dev/db/migration"

jwt:
  cookie:
    secure: true

cors:
  allowed-origins: https://${ADMIN_BASE_URL}

logging:
  level:
    org:
      springframework: DEBUG