spring:
  config:
    activate:
      on-profile: dev
  flyway:
    locations: "classpath:db/migration,classpath:dev/db/migration"

jwt:
  cookie:
    secure: false

cors:
  allowed-origins: http://localhost:5173, http://localhost:4321

logging:
  level:
    org:
      springframework: DEBUG