spring:
  config:
    activate:
      on-profile: dev
    import: file:../../dev.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
  flyway:
    locations: "classpath:db/migration,classpath:dev/db/migration"

server:
  servlet:
    session:
      cookie:
        secure: false

jwt:
  cookieSecure: false

cors:
  allowed-origins: http://localhost:5173, http://localhost:4321

logging:
  level:
    org:
      springframework: DEBUG