spring:
  application:
    name: gjuplans
  datasource:
    url: jdbc:postgresql://database:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    clean-disabled: true
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

jwt:
  cookieExpiry: ${JWT_COOKIEEXPIRY}

cors:
  allowed-origins: ${ALLOWED_ORIGINS}

backend:
  api:
    key: ${BACKEND_API_KEY}
