spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}

server:
  servlet:
    session:
      cookie:
        secure: true
  forward-headers-strategy: native

jwt:
  cookieSecure: true

cors:
  allowed-origins: https://admin.gjuplans.com

logging:
  level:
    root: WARN