version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: gjuplans-database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./services/backend
      dockerfile: dev.Dockerfile
    container_name: gjuplans-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_SECURITY_USER_NAME: ${SPRING_SECURITY_USER_NAME}
      SPRING_SECURITY_USER_PASSWORD: ${SPRING_SECURITY_USER_PASSWORD}
      JWT_COOKIEEXPIRY: ${JWT_COOKIEEXPIRY}
      BACKEND_API_KEY: ${BACKEND_API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  dashboard:
    build:
      context: .
      dockerfile: apps/dashboard/dev.Dockerfile
    container_name: gjuplans-dashboard
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:8080

  pages:
    build:
      context: .
      dockerfile: apps/pages/dev.Dockerfile
    container_name: gjuplans-pages
    ports:
      - "4321:4321"
    depends_on:
      - backend
    environment:
      PUBLIC_API_URL: http://localhost:8080

volumes:
  postgres-data:
