services:
  dev_container:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: dev-container
    env_file: dev.env
    volumes:
      - .:/workspace
      - node_modules:/workspace/node_modules
      - maven_cache:/root/.m2
    working_dir: /workspace
    stdin_open: true
    tty: true

  database:
    image: postgres:17.4-alpine
    container_name: gjuplans-database
    env_file: dev.env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  db:
  node_modules:
  maven_cache:
