services:
  database:
    image: postgres:17.4-alpine
    container_name: postgres
    env_file: dev.env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  db: