services:
  database:
    image: postgres:17.4-alpine
    container_name: gjuplans-database
    env_file: dev.env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

  backend:
    build:
      context: ./services/backend
      dockerfile: dev.Dockerfile
    container_name: gjuplans-backend
    env_file: dev.env
    ports:
      - "8080:8080"
    depends_on:
      - database
    volumes:
      - /root/.m2
      - ./services/backend:/app:cached

  dashboard:
    build:
      context: .
      dockerfile: apps/dashboard/Dockerfile
    container_name: gjuplans-dashboard
    env_file: dev.env
    ports:
      - "5173:5173"
    volumes:
      - .:/app:cached
      - /app/node_modules

  pages:
    build:
      context: .
      dockerfile: apps/pages/Dockerfile
    container_name: gjuplans-pages
    env_file: dev.env
    ports:
      - "4321:4321"
    depends_on:
      - backend
    volumes:
      - .:/app:cached
      - /app/node_modules

volumes:
  db:
