services:
  database:
    image: postgres:17.4-alpine
    container_name: gjuplans-database
    env_file: dev.env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

  backend:
    build:
      context: ./services/backend
      dockerfile: dev.Dockerfile
    container_name: gjuplans-backend
    env_file: dev.env
    ports:
      - "8080:8080"
    depends_on:
      - database

  dashboard:
    build:
      context: .
      dockerfile: .devcontainer/dashboard/dev.Dockerfile
    container_name: gjuplans-dashboard
    env_file: dev.env
    ports:
      - "5173:5173"
    depends_on:
      - backend

  pages:
    build:
      context: .
      dockerfile: apps/pages/dev.Dockerfile
    container_name: gjuplans-pages
    env_file: dev.env
    ports:
      - "4321:4321"
    depends_on:
      - backend

volumes:
  db: