services:
  backend:
    image: gjuplans/backend:${BACKEND_IMAGE_TAG}
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      BACKEND_API_KEY: ${BACKEND_API_KEY}
      ADMIN_BASE_URL: ${ADMIN_BASE_URL}
    networks:
      - caddy
    depends_on:
      - database
    restart: always

  database:
    image: postgres:16.9-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  reverse_proxy:
    image: caddy:2.10.0-alpine
    environment:
      ADMIN_BASE_URL: ${ADMIN_BASE_URL}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy
    restart: always

networks:
  caddy:

volumes:
  pg_data:
  caddy_data:
  caddy_config:
