spring:
  application:
    name: gjuplans
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:postgresql://localhost:5432/gjuplans
    username: postgres
    password: admin
jwt:
  cookieExpiry: 1800
backend:
  api:
    key: ${BACKEND_API_KEY}