name: gjuplans-backend

services:
  backend:
    container_name: backend
    build:
      context: .
      target: build
    command: ./mvnw spring-boot:run
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      BACKEND_API_KEY: ${BACKEND_API_KEY}
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: postgres:16.9-alpine
    container_name: database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data: