spring:
  application:
    name: flowstruct-api
  datasource:
    url: jdbc:postgresql://database/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    clean-disabled: true
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

jwt:
  cookie:
    expiry: 1800

server:
  forward-headers-strategy: native

cors:
  allowed-origins: ${CMS_DOMAIN}

secure: ${SECURE}

api:
  key: ${API_KEY}
