spring:
  application:
    name: flowstruct-api
  datasource:
    url: jdbc:postgresql://database/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    clean-disabled: true
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
    user: ${DB_USER}
    password: ${DB_PASSWORD}

jwt:
  cookie:
    expiry: 1800

server:
  forward-headers-strategy: native

cors:
  allowed-origins: ${CMS_DOMAIN}

secure: ${SECURE}

api:
  key: ${API_KEY}
