spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/${DB_NAME:flowstruct}
  config:
    activate:
      on-profile: dev
    import: file:.env[.properties]
  flyway:
    locations: "classpath:db/migration,classpath:dev/db/migration"

logging:
  level:
    org:
      springframework: DEBUG