ALTER TABLE "user"
    ADD COLUMN email VARCHAR(255);

UPDATE "user"
SET email = LOWER(CONCAT(username, '@gju.edu.jo'))
WHERE email IS NULL;

ALTER TABLE "user"
    ALTER COLUMN email SET NOT NULL;

ALTER TABLE "user"
    ADD CONSTRAINT user_email_key UNIQUE (email);

ALTER TABLE "user"
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
