ALTER TABLE "user"
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ADD COLUMN updated_by INT,
    ADD CONSTRAINT user_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES "user"(id);
