ALTER TABLE program
    ADD COLUMN status VARCHAR(255) DEFAULT ('DRAFT') NOT NULL,
    ADD COLUMN draft  JSONB;

ALTER TABLE study_plan
    DROP COLUMN is_published,
    ADD COLUMN status VARCHAR(255) DEFAULT ('DRAFT') NOT NULL,
    ADD COLUMN draft  JSONB;

ALTER TABLE course
    ADD COLUMN status VARCHAR(255) DEFAULT ('DRAFT') NOT NULL,
    ADD COLUMN draft  JSONB;