ALTER TABLE program
    ADD COLUMN is_archived BOOLEAN DEFAULT FALSE;
ALTER TABLE study_plan
    ADD COLUMN is_archived BOOLEAN DEFAULT FALSE;
ALTER TABLE course
    ADD COLUMN is_archived BOOLEAN DEFAULT FALSE;