ALTER TABLE program
    ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE study_plan
    ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE course
    ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;