/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout/route'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutStudyPlansRouteImport } from './routes/_layout/study-plans/route'
import { Route as LayoutProgramsRouteImport } from './routes/_layout/programs/route'
import { Route as LayoutCoursesRouteImport } from './routes/_layout/courses/route'
import { Route as LayoutStudyPlansIndexImport } from './routes/_layout/study-plans/index'
import { Route as LayoutProgramsIndexImport } from './routes/_layout/programs/index'
import { Route as LayoutCoursesIndexImport } from './routes/_layout/courses/index'
import { Route as LayoutStudyPlansNewImport } from './routes/_layout/study-plans/new'
import { Route as LayoutProgramsNewImport } from './routes/_layout/programs/new'
import { Route as LayoutCoursesNewImport } from './routes/_layout/courses/new'
import { Route as LayoutStudyPlansStudyPlanIdRouteImport } from './routes/_layout/study-plans/$studyPlanId/route'
import { Route as LayoutProgramsProgramIdRouteImport } from './routes/_layout/programs/$programId/route'
import { Route as LayoutCoursesCourseIdRouteImport } from './routes/_layout/courses/$courseId/route'
import { Route as LayoutStudyPlansStudyPlanIdIndexImport } from './routes/_layout/study-plans/$studyPlanId/index'
import { Route as LayoutProgramsProgramIdIndexImport } from './routes/_layout/programs/$programId/index'
import { Route as LayoutCoursesCourseIdIndexImport } from './routes/_layout/courses/$courseId/index'
import { Route as LayoutStudyPlansStudyPlanIdProgramMapImport } from './routes/_layout/study-plans/$studyPlanId/program-map'
import { Route as LayoutStudyPlansStudyPlanIdFrameworkImport } from './routes/_layout/study-plans/$studyPlanId/framework'
import { Route as LayoutProgramsProgramIdEditImport } from './routes/_layout/programs/$programId/edit'
import { Route as LayoutCoursesCourseIdEditImport } from './routes/_layout/courses/$courseId/edit'
import { Route as LayoutStudyPlansStudyPlanIdDetailsRouteImport } from './routes/_layout/study-plans/$studyPlanId/details/route'
import { Route as LayoutStudyPlansStudyPlanIdSectionsIndexImport } from './routes/_layout/study-plans/$studyPlanId/sections/index'
import { Route as LayoutStudyPlansStudyPlanIdDetailsIndexImport } from './routes/_layout/study-plans/$studyPlanId/details/index'
import { Route as LayoutStudyPlansStudyPlanIdSectionsNewImport } from './routes/_layout/study-plans/$studyPlanId/sections/new'
import { Route as LayoutStudyPlansStudyPlanIdDetailsEditImport } from './routes/_layout/study-plans/$studyPlanId/details/edit'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRouteRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutStudyPlansRouteRoute = LayoutStudyPlansRouteImport.update({
  id: '/study-plans',
  path: '/study-plans',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutProgramsRouteRoute = LayoutProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutCoursesRouteRoute = LayoutCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutStudyPlansIndexRoute = LayoutStudyPlansIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutStudyPlansRouteRoute,
} as any)

const LayoutProgramsIndexRoute = LayoutProgramsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutProgramsRouteRoute,
} as any)

const LayoutCoursesIndexRoute = LayoutCoursesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutCoursesRouteRoute,
} as any)

const LayoutStudyPlansNewRoute = LayoutStudyPlansNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutStudyPlansRouteRoute,
} as any)

const LayoutProgramsNewRoute = LayoutProgramsNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutProgramsRouteRoute,
} as any)

const LayoutCoursesNewRoute = LayoutCoursesNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutCoursesRouteRoute,
} as any)

const LayoutStudyPlansStudyPlanIdRouteRoute =
  LayoutStudyPlansStudyPlanIdRouteImport.update({
    id: '/$studyPlanId',
    path: '/$studyPlanId',
    getParentRoute: () => LayoutStudyPlansRouteRoute,
  } as any)

const LayoutProgramsProgramIdRouteRoute =
  LayoutProgramsProgramIdRouteImport.update({
    id: '/$programId',
    path: '/$programId',
    getParentRoute: () => LayoutProgramsRouteRoute,
  } as any)

const LayoutCoursesCourseIdRouteRoute = LayoutCoursesCourseIdRouteImport.update(
  {
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => LayoutCoursesRouteRoute,
  } as any,
)

const LayoutStudyPlansStudyPlanIdIndexRoute =
  LayoutStudyPlansStudyPlanIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

const LayoutProgramsProgramIdIndexRoute =
  LayoutProgramsProgramIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutProgramsProgramIdRouteRoute,
  } as any)

const LayoutCoursesCourseIdIndexRoute = LayoutCoursesCourseIdIndexImport.update(
  {
    id: '/',
    path: '/',
    getParentRoute: () => LayoutCoursesCourseIdRouteRoute,
  } as any,
)

const LayoutStudyPlansStudyPlanIdProgramMapRoute =
  LayoutStudyPlansStudyPlanIdProgramMapImport.update({
    id: '/program-map',
    path: '/program-map',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

const LayoutStudyPlansStudyPlanIdFrameworkRoute =
  LayoutStudyPlansStudyPlanIdFrameworkImport.update({
    id: '/framework',
    path: '/framework',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

const LayoutProgramsProgramIdEditRoute =
  LayoutProgramsProgramIdEditImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => LayoutProgramsProgramIdRouteRoute,
  } as any)

const LayoutCoursesCourseIdEditRoute = LayoutCoursesCourseIdEditImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => LayoutCoursesCourseIdRouteRoute,
} as any)

const LayoutStudyPlansStudyPlanIdDetailsRouteRoute =
  LayoutStudyPlansStudyPlanIdDetailsRouteImport.update({
    id: '/details',
    path: '/details',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

const LayoutStudyPlansStudyPlanIdSectionsIndexRoute =
  LayoutStudyPlansStudyPlanIdSectionsIndexImport.update({
    id: '/sections/',
    path: '/sections/',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

const LayoutStudyPlansStudyPlanIdDetailsIndexRoute =
  LayoutStudyPlansStudyPlanIdDetailsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdDetailsRouteRoute,
  } as any)

const LayoutStudyPlansStudyPlanIdSectionsNewRoute =
  LayoutStudyPlansStudyPlanIdSectionsNewImport.update({
    id: '/sections/new',
    path: '/sections/new',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

const LayoutStudyPlansStudyPlanIdDetailsEditRoute =
  LayoutStudyPlansStudyPlanIdDetailsEditImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdDetailsRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_layout/courses': {
      id: '/_layout/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof LayoutCoursesRouteImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/programs': {
      id: '/_layout/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof LayoutProgramsRouteImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/study-plans': {
      id: '/_layout/study-plans'
      path: '/study-plans'
      fullPath: '/study-plans'
      preLoaderRoute: typeof LayoutStudyPlansRouteImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/courses/$courseId': {
      id: '/_layout/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof LayoutCoursesCourseIdRouteImport
      parentRoute: typeof LayoutCoursesRouteImport
    }
    '/_layout/programs/$programId': {
      id: '/_layout/programs/$programId'
      path: '/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof LayoutProgramsProgramIdRouteImport
      parentRoute: typeof LayoutProgramsRouteImport
    }
    '/_layout/study-plans/$studyPlanId': {
      id: '/_layout/study-plans/$studyPlanId'
      path: '/$studyPlanId'
      fullPath: '/study-plans/$studyPlanId'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
      parentRoute: typeof LayoutStudyPlansRouteImport
    }
    '/_layout/courses/new': {
      id: '/_layout/courses/new'
      path: '/new'
      fullPath: '/courses/new'
      preLoaderRoute: typeof LayoutCoursesNewImport
      parentRoute: typeof LayoutCoursesRouteImport
    }
    '/_layout/programs/new': {
      id: '/_layout/programs/new'
      path: '/new'
      fullPath: '/programs/new'
      preLoaderRoute: typeof LayoutProgramsNewImport
      parentRoute: typeof LayoutProgramsRouteImport
    }
    '/_layout/study-plans/new': {
      id: '/_layout/study-plans/new'
      path: '/new'
      fullPath: '/study-plans/new'
      preLoaderRoute: typeof LayoutStudyPlansNewImport
      parentRoute: typeof LayoutStudyPlansRouteImport
    }
    '/_layout/courses/': {
      id: '/_layout/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof LayoutCoursesIndexImport
      parentRoute: typeof LayoutCoursesRouteImport
    }
    '/_layout/programs/': {
      id: '/_layout/programs/'
      path: '/'
      fullPath: '/programs/'
      preLoaderRoute: typeof LayoutProgramsIndexImport
      parentRoute: typeof LayoutProgramsRouteImport
    }
    '/_layout/study-plans/': {
      id: '/_layout/study-plans/'
      path: '/'
      fullPath: '/study-plans/'
      preLoaderRoute: typeof LayoutStudyPlansIndexImport
      parentRoute: typeof LayoutStudyPlansRouteImport
    }
    '/_layout/study-plans/$studyPlanId/details': {
      id: '/_layout/study-plans/$studyPlanId/details'
      path: '/details'
      fullPath: '/study-plans/$studyPlanId/details'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdDetailsRouteImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
    '/_layout/courses/$courseId/edit': {
      id: '/_layout/courses/$courseId/edit'
      path: '/edit'
      fullPath: '/courses/$courseId/edit'
      preLoaderRoute: typeof LayoutCoursesCourseIdEditImport
      parentRoute: typeof LayoutCoursesCourseIdRouteImport
    }
    '/_layout/programs/$programId/edit': {
      id: '/_layout/programs/$programId/edit'
      path: '/edit'
      fullPath: '/programs/$programId/edit'
      preLoaderRoute: typeof LayoutProgramsProgramIdEditImport
      parentRoute: typeof LayoutProgramsProgramIdRouteImport
    }
    '/_layout/study-plans/$studyPlanId/framework': {
      id: '/_layout/study-plans/$studyPlanId/framework'
      path: '/framework'
      fullPath: '/study-plans/$studyPlanId/framework'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdFrameworkImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
    '/_layout/study-plans/$studyPlanId/program-map': {
      id: '/_layout/study-plans/$studyPlanId/program-map'
      path: '/program-map'
      fullPath: '/study-plans/$studyPlanId/program-map'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdProgramMapImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
    '/_layout/courses/$courseId/': {
      id: '/_layout/courses/$courseId/'
      path: '/'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof LayoutCoursesCourseIdIndexImport
      parentRoute: typeof LayoutCoursesCourseIdRouteImport
    }
    '/_layout/programs/$programId/': {
      id: '/_layout/programs/$programId/'
      path: '/'
      fullPath: '/programs/$programId/'
      preLoaderRoute: typeof LayoutProgramsProgramIdIndexImport
      parentRoute: typeof LayoutProgramsProgramIdRouteImport
    }
    '/_layout/study-plans/$studyPlanId/': {
      id: '/_layout/study-plans/$studyPlanId/'
      path: '/'
      fullPath: '/study-plans/$studyPlanId/'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdIndexImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
    '/_layout/study-plans/$studyPlanId/details/edit': {
      id: '/_layout/study-plans/$studyPlanId/details/edit'
      path: '/edit'
      fullPath: '/study-plans/$studyPlanId/details/edit'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdDetailsEditImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdDetailsRouteImport
    }
    '/_layout/study-plans/$studyPlanId/sections/new': {
      id: '/_layout/study-plans/$studyPlanId/sections/new'
      path: '/sections/new'
      fullPath: '/study-plans/$studyPlanId/sections/new'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdSectionsNewImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
    '/_layout/study-plans/$studyPlanId/details/': {
      id: '/_layout/study-plans/$studyPlanId/details/'
      path: '/'
      fullPath: '/study-plans/$studyPlanId/details/'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdDetailsIndexImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdDetailsRouteImport
    }
    '/_layout/study-plans/$studyPlanId/sections/': {
      id: '/_layout/study-plans/$studyPlanId/sections/'
      path: '/sections'
      fullPath: '/study-plans/$studyPlanId/sections'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdSectionsIndexImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
  }
}

// Create and export the route tree

interface LayoutCoursesCourseIdRouteRouteChildren {
  LayoutCoursesCourseIdEditRoute: typeof LayoutCoursesCourseIdEditRoute
  LayoutCoursesCourseIdIndexRoute: typeof LayoutCoursesCourseIdIndexRoute
}

const LayoutCoursesCourseIdRouteRouteChildren: LayoutCoursesCourseIdRouteRouteChildren =
  {
    LayoutCoursesCourseIdEditRoute: LayoutCoursesCourseIdEditRoute,
    LayoutCoursesCourseIdIndexRoute: LayoutCoursesCourseIdIndexRoute,
  }

const LayoutCoursesCourseIdRouteRouteWithChildren =
  LayoutCoursesCourseIdRouteRoute._addFileChildren(
    LayoutCoursesCourseIdRouteRouteChildren,
  )

interface LayoutCoursesRouteRouteChildren {
  LayoutCoursesCourseIdRouteRoute: typeof LayoutCoursesCourseIdRouteRouteWithChildren
  LayoutCoursesNewRoute: typeof LayoutCoursesNewRoute
  LayoutCoursesIndexRoute: typeof LayoutCoursesIndexRoute
}

const LayoutCoursesRouteRouteChildren: LayoutCoursesRouteRouteChildren = {
  LayoutCoursesCourseIdRouteRoute: LayoutCoursesCourseIdRouteRouteWithChildren,
  LayoutCoursesNewRoute: LayoutCoursesNewRoute,
  LayoutCoursesIndexRoute: LayoutCoursesIndexRoute,
}

const LayoutCoursesRouteRouteWithChildren =
  LayoutCoursesRouteRoute._addFileChildren(LayoutCoursesRouteRouteChildren)

interface LayoutProgramsProgramIdRouteRouteChildren {
  LayoutProgramsProgramIdEditRoute: typeof LayoutProgramsProgramIdEditRoute
  LayoutProgramsProgramIdIndexRoute: typeof LayoutProgramsProgramIdIndexRoute
}

const LayoutProgramsProgramIdRouteRouteChildren: LayoutProgramsProgramIdRouteRouteChildren =
  {
    LayoutProgramsProgramIdEditRoute: LayoutProgramsProgramIdEditRoute,
    LayoutProgramsProgramIdIndexRoute: LayoutProgramsProgramIdIndexRoute,
  }

const LayoutProgramsProgramIdRouteRouteWithChildren =
  LayoutProgramsProgramIdRouteRoute._addFileChildren(
    LayoutProgramsProgramIdRouteRouteChildren,
  )

interface LayoutProgramsRouteRouteChildren {
  LayoutProgramsProgramIdRouteRoute: typeof LayoutProgramsProgramIdRouteRouteWithChildren
  LayoutProgramsNewRoute: typeof LayoutProgramsNewRoute
  LayoutProgramsIndexRoute: typeof LayoutProgramsIndexRoute
}

const LayoutProgramsRouteRouteChildren: LayoutProgramsRouteRouteChildren = {
  LayoutProgramsProgramIdRouteRoute:
    LayoutProgramsProgramIdRouteRouteWithChildren,
  LayoutProgramsNewRoute: LayoutProgramsNewRoute,
  LayoutProgramsIndexRoute: LayoutProgramsIndexRoute,
}

const LayoutProgramsRouteRouteWithChildren =
  LayoutProgramsRouteRoute._addFileChildren(LayoutProgramsRouteRouteChildren)

interface LayoutStudyPlansStudyPlanIdDetailsRouteRouteChildren {
  LayoutStudyPlansStudyPlanIdDetailsEditRoute: typeof LayoutStudyPlansStudyPlanIdDetailsEditRoute
  LayoutStudyPlansStudyPlanIdDetailsIndexRoute: typeof LayoutStudyPlansStudyPlanIdDetailsIndexRoute
}

const LayoutStudyPlansStudyPlanIdDetailsRouteRouteChildren: LayoutStudyPlansStudyPlanIdDetailsRouteRouteChildren =
  {
    LayoutStudyPlansStudyPlanIdDetailsEditRoute:
      LayoutStudyPlansStudyPlanIdDetailsEditRoute,
    LayoutStudyPlansStudyPlanIdDetailsIndexRoute:
      LayoutStudyPlansStudyPlanIdDetailsIndexRoute,
  }

const LayoutStudyPlansStudyPlanIdDetailsRouteRouteWithChildren =
  LayoutStudyPlansStudyPlanIdDetailsRouteRoute._addFileChildren(
    LayoutStudyPlansStudyPlanIdDetailsRouteRouteChildren,
  )

interface LayoutStudyPlansStudyPlanIdRouteRouteChildren {
  LayoutStudyPlansStudyPlanIdDetailsRouteRoute: typeof LayoutStudyPlansStudyPlanIdDetailsRouteRouteWithChildren
  LayoutStudyPlansStudyPlanIdFrameworkRoute: typeof LayoutStudyPlansStudyPlanIdFrameworkRoute
  LayoutStudyPlansStudyPlanIdProgramMapRoute: typeof LayoutStudyPlansStudyPlanIdProgramMapRoute
  LayoutStudyPlansStudyPlanIdIndexRoute: typeof LayoutStudyPlansStudyPlanIdIndexRoute
  LayoutStudyPlansStudyPlanIdSectionsNewRoute: typeof LayoutStudyPlansStudyPlanIdSectionsNewRoute
  LayoutStudyPlansStudyPlanIdSectionsIndexRoute: typeof LayoutStudyPlansStudyPlanIdSectionsIndexRoute
}

const LayoutStudyPlansStudyPlanIdRouteRouteChildren: LayoutStudyPlansStudyPlanIdRouteRouteChildren =
  {
    LayoutStudyPlansStudyPlanIdDetailsRouteRoute:
      LayoutStudyPlansStudyPlanIdDetailsRouteRouteWithChildren,
    LayoutStudyPlansStudyPlanIdFrameworkRoute:
      LayoutStudyPlansStudyPlanIdFrameworkRoute,
    LayoutStudyPlansStudyPlanIdProgramMapRoute:
      LayoutStudyPlansStudyPlanIdProgramMapRoute,
    LayoutStudyPlansStudyPlanIdIndexRoute:
      LayoutStudyPlansStudyPlanIdIndexRoute,
    LayoutStudyPlansStudyPlanIdSectionsNewRoute:
      LayoutStudyPlansStudyPlanIdSectionsNewRoute,
    LayoutStudyPlansStudyPlanIdSectionsIndexRoute:
      LayoutStudyPlansStudyPlanIdSectionsIndexRoute,
  }

const LayoutStudyPlansStudyPlanIdRouteRouteWithChildren =
  LayoutStudyPlansStudyPlanIdRouteRoute._addFileChildren(
    LayoutStudyPlansStudyPlanIdRouteRouteChildren,
  )

interface LayoutStudyPlansRouteRouteChildren {
  LayoutStudyPlansStudyPlanIdRouteRoute: typeof LayoutStudyPlansStudyPlanIdRouteRouteWithChildren
  LayoutStudyPlansNewRoute: typeof LayoutStudyPlansNewRoute
  LayoutStudyPlansIndexRoute: typeof LayoutStudyPlansIndexRoute
}

const LayoutStudyPlansRouteRouteChildren: LayoutStudyPlansRouteRouteChildren = {
  LayoutStudyPlansStudyPlanIdRouteRoute:
    LayoutStudyPlansStudyPlanIdRouteRouteWithChildren,
  LayoutStudyPlansNewRoute: LayoutStudyPlansNewRoute,
  LayoutStudyPlansIndexRoute: LayoutStudyPlansIndexRoute,
}

const LayoutStudyPlansRouteRouteWithChildren =
  LayoutStudyPlansRouteRoute._addFileChildren(
    LayoutStudyPlansRouteRouteChildren,
  )

interface LayoutRouteRouteChildren {
  LayoutCoursesRouteRoute: typeof LayoutCoursesRouteRouteWithChildren
  LayoutProgramsRouteRoute: typeof LayoutProgramsRouteRouteWithChildren
  LayoutStudyPlansRouteRoute: typeof LayoutStudyPlansRouteRouteWithChildren
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutCoursesRouteRoute: LayoutCoursesRouteRouteWithChildren,
  LayoutProgramsRouteRoute: LayoutProgramsRouteRouteWithChildren,
  LayoutStudyPlansRouteRoute: LayoutStudyPlansRouteRouteWithChildren,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/courses': typeof LayoutCoursesRouteRouteWithChildren
  '/programs': typeof LayoutProgramsRouteRouteWithChildren
  '/study-plans': typeof LayoutStudyPlansRouteRouteWithChildren
  '/courses/$courseId': typeof LayoutCoursesCourseIdRouteRouteWithChildren
  '/programs/$programId': typeof LayoutProgramsProgramIdRouteRouteWithChildren
  '/study-plans/$studyPlanId': typeof LayoutStudyPlansStudyPlanIdRouteRouteWithChildren
  '/courses/new': typeof LayoutCoursesNewRoute
  '/programs/new': typeof LayoutProgramsNewRoute
  '/study-plans/new': typeof LayoutStudyPlansNewRoute
  '/courses/': typeof LayoutCoursesIndexRoute
  '/programs/': typeof LayoutProgramsIndexRoute
  '/study-plans/': typeof LayoutStudyPlansIndexRoute
  '/study-plans/$studyPlanId/details': typeof LayoutStudyPlansStudyPlanIdDetailsRouteRouteWithChildren
  '/courses/$courseId/edit': typeof LayoutCoursesCourseIdEditRoute
  '/programs/$programId/edit': typeof LayoutProgramsProgramIdEditRoute
  '/study-plans/$studyPlanId/framework': typeof LayoutStudyPlansStudyPlanIdFrameworkRoute
  '/study-plans/$studyPlanId/program-map': typeof LayoutStudyPlansStudyPlanIdProgramMapRoute
  '/courses/$courseId/': typeof LayoutCoursesCourseIdIndexRoute
  '/programs/$programId/': typeof LayoutProgramsProgramIdIndexRoute
  '/study-plans/$studyPlanId/': typeof LayoutStudyPlansStudyPlanIdIndexRoute
  '/study-plans/$studyPlanId/details/edit': typeof LayoutStudyPlansStudyPlanIdDetailsEditRoute
  '/study-plans/$studyPlanId/sections/new': typeof LayoutStudyPlansStudyPlanIdSectionsNewRoute
  '/study-plans/$studyPlanId/details/': typeof LayoutStudyPlansStudyPlanIdDetailsIndexRoute
  '/study-plans/$studyPlanId/sections': typeof LayoutStudyPlansStudyPlanIdSectionsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/courses/new': typeof LayoutCoursesNewRoute
  '/programs/new': typeof LayoutProgramsNewRoute
  '/study-plans/new': typeof LayoutStudyPlansNewRoute
  '/courses': typeof LayoutCoursesIndexRoute
  '/programs': typeof LayoutProgramsIndexRoute
  '/study-plans': typeof LayoutStudyPlansIndexRoute
  '/courses/$courseId/edit': typeof LayoutCoursesCourseIdEditRoute
  '/programs/$programId/edit': typeof LayoutProgramsProgramIdEditRoute
  '/study-plans/$studyPlanId/framework': typeof LayoutStudyPlansStudyPlanIdFrameworkRoute
  '/study-plans/$studyPlanId/program-map': typeof LayoutStudyPlansStudyPlanIdProgramMapRoute
  '/courses/$courseId': typeof LayoutCoursesCourseIdIndexRoute
  '/programs/$programId': typeof LayoutProgramsProgramIdIndexRoute
  '/study-plans/$studyPlanId': typeof LayoutStudyPlansStudyPlanIdIndexRoute
  '/study-plans/$studyPlanId/details/edit': typeof LayoutStudyPlansStudyPlanIdDetailsEditRoute
  '/study-plans/$studyPlanId/sections/new': typeof LayoutStudyPlansStudyPlanIdSectionsNewRoute
  '/study-plans/$studyPlanId/details': typeof LayoutStudyPlansStudyPlanIdDetailsIndexRoute
  '/study-plans/$studyPlanId/sections': typeof LayoutStudyPlansStudyPlanIdSectionsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/courses': typeof LayoutCoursesRouteRouteWithChildren
  '/_layout/programs': typeof LayoutProgramsRouteRouteWithChildren
  '/_layout/study-plans': typeof LayoutStudyPlansRouteRouteWithChildren
  '/_layout/courses/$courseId': typeof LayoutCoursesCourseIdRouteRouteWithChildren
  '/_layout/programs/$programId': typeof LayoutProgramsProgramIdRouteRouteWithChildren
  '/_layout/study-plans/$studyPlanId': typeof LayoutStudyPlansStudyPlanIdRouteRouteWithChildren
  '/_layout/courses/new': typeof LayoutCoursesNewRoute
  '/_layout/programs/new': typeof LayoutProgramsNewRoute
  '/_layout/study-plans/new': typeof LayoutStudyPlansNewRoute
  '/_layout/courses/': typeof LayoutCoursesIndexRoute
  '/_layout/programs/': typeof LayoutProgramsIndexRoute
  '/_layout/study-plans/': typeof LayoutStudyPlansIndexRoute
  '/_layout/study-plans/$studyPlanId/details': typeof LayoutStudyPlansStudyPlanIdDetailsRouteRouteWithChildren
  '/_layout/courses/$courseId/edit': typeof LayoutCoursesCourseIdEditRoute
  '/_layout/programs/$programId/edit': typeof LayoutProgramsProgramIdEditRoute
  '/_layout/study-plans/$studyPlanId/framework': typeof LayoutStudyPlansStudyPlanIdFrameworkRoute
  '/_layout/study-plans/$studyPlanId/program-map': typeof LayoutStudyPlansStudyPlanIdProgramMapRoute
  '/_layout/courses/$courseId/': typeof LayoutCoursesCourseIdIndexRoute
  '/_layout/programs/$programId/': typeof LayoutProgramsProgramIdIndexRoute
  '/_layout/study-plans/$studyPlanId/': typeof LayoutStudyPlansStudyPlanIdIndexRoute
  '/_layout/study-plans/$studyPlanId/details/edit': typeof LayoutStudyPlansStudyPlanIdDetailsEditRoute
  '/_layout/study-plans/$studyPlanId/sections/new': typeof LayoutStudyPlansStudyPlanIdSectionsNewRoute
  '/_layout/study-plans/$studyPlanId/details/': typeof LayoutStudyPlansStudyPlanIdDetailsIndexRoute
  '/_layout/study-plans/$studyPlanId/sections/': typeof LayoutStudyPlansStudyPlanIdSectionsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/courses'
    | '/programs'
    | '/study-plans'
    | '/courses/$courseId'
    | '/programs/$programId'
    | '/study-plans/$studyPlanId'
    | '/courses/new'
    | '/programs/new'
    | '/study-plans/new'
    | '/courses/'
    | '/programs/'
    | '/study-plans/'
    | '/study-plans/$studyPlanId/details'
    | '/courses/$courseId/edit'
    | '/programs/$programId/edit'
    | '/study-plans/$studyPlanId/framework'
    | '/study-plans/$studyPlanId/program-map'
    | '/courses/$courseId/'
    | '/programs/$programId/'
    | '/study-plans/$studyPlanId/'
    | '/study-plans/$studyPlanId/details/edit'
    | '/study-plans/$studyPlanId/sections/new'
    | '/study-plans/$studyPlanId/details/'
    | '/study-plans/$studyPlanId/sections'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/courses/new'
    | '/programs/new'
    | '/study-plans/new'
    | '/courses'
    | '/programs'
    | '/study-plans'
    | '/courses/$courseId/edit'
    | '/programs/$programId/edit'
    | '/study-plans/$studyPlanId/framework'
    | '/study-plans/$studyPlanId/program-map'
    | '/courses/$courseId'
    | '/programs/$programId'
    | '/study-plans/$studyPlanId'
    | '/study-plans/$studyPlanId/details/edit'
    | '/study-plans/$studyPlanId/sections/new'
    | '/study-plans/$studyPlanId/details'
    | '/study-plans/$studyPlanId/sections'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/_layout/courses'
    | '/_layout/programs'
    | '/_layout/study-plans'
    | '/_layout/courses/$courseId'
    | '/_layout/programs/$programId'
    | '/_layout/study-plans/$studyPlanId'
    | '/_layout/courses/new'
    | '/_layout/programs/new'
    | '/_layout/study-plans/new'
    | '/_layout/courses/'
    | '/_layout/programs/'
    | '/_layout/study-plans/'
    | '/_layout/study-plans/$studyPlanId/details'
    | '/_layout/courses/$courseId/edit'
    | '/_layout/programs/$programId/edit'
    | '/_layout/study-plans/$studyPlanId/framework'
    | '/_layout/study-plans/$studyPlanId/program-map'
    | '/_layout/courses/$courseId/'
    | '/_layout/programs/$programId/'
    | '/_layout/study-plans/$studyPlanId/'
    | '/_layout/study-plans/$studyPlanId/details/edit'
    | '/_layout/study-plans/$studyPlanId/sections/new'
    | '/_layout/study-plans/$studyPlanId/details/'
    | '/_layout/study-plans/$studyPlanId/sections/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout/route.tsx",
      "children": [
        "/_layout/courses",
        "/_layout/programs",
        "/_layout/study-plans"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_layout/courses": {
      "filePath": "_layout/courses/route.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/courses/$courseId",
        "/_layout/courses/new",
        "/_layout/courses/"
      ]
    },
    "/_layout/programs": {
      "filePath": "_layout/programs/route.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/programs/$programId",
        "/_layout/programs/new",
        "/_layout/programs/"
      ]
    },
    "/_layout/study-plans": {
      "filePath": "_layout/study-plans/route.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/study-plans/$studyPlanId",
        "/_layout/study-plans/new",
        "/_layout/study-plans/"
      ]
    },
    "/_layout/courses/$courseId": {
      "filePath": "_layout/courses/$courseId/route.tsx",
      "parent": "/_layout/courses",
      "children": [
        "/_layout/courses/$courseId/edit",
        "/_layout/courses/$courseId/"
      ]
    },
    "/_layout/programs/$programId": {
      "filePath": "_layout/programs/$programId/route.tsx",
      "parent": "/_layout/programs",
      "children": [
        "/_layout/programs/$programId/edit",
        "/_layout/programs/$programId/"
      ]
    },
    "/_layout/study-plans/$studyPlanId": {
      "filePath": "_layout/study-plans/$studyPlanId/route.tsx",
      "parent": "/_layout/study-plans",
      "children": [
        "/_layout/study-plans/$studyPlanId/details",
        "/_layout/study-plans/$studyPlanId/framework",
        "/_layout/study-plans/$studyPlanId/program-map",
        "/_layout/study-plans/$studyPlanId/",
        "/_layout/study-plans/$studyPlanId/sections/new",
        "/_layout/study-plans/$studyPlanId/sections/"
      ]
    },
    "/_layout/courses/new": {
      "filePath": "_layout/courses/new.tsx",
      "parent": "/_layout/courses"
    },
    "/_layout/programs/new": {
      "filePath": "_layout/programs/new.tsx",
      "parent": "/_layout/programs"
    },
    "/_layout/study-plans/new": {
      "filePath": "_layout/study-plans/new.tsx",
      "parent": "/_layout/study-plans"
    },
    "/_layout/courses/": {
      "filePath": "_layout/courses/index.tsx",
      "parent": "/_layout/courses"
    },
    "/_layout/programs/": {
      "filePath": "_layout/programs/index.tsx",
      "parent": "/_layout/programs"
    },
    "/_layout/study-plans/": {
      "filePath": "_layout/study-plans/index.tsx",
      "parent": "/_layout/study-plans"
    },
    "/_layout/study-plans/$studyPlanId/details": {
      "filePath": "_layout/study-plans/$studyPlanId/details/route.tsx",
      "parent": "/_layout/study-plans/$studyPlanId",
      "children": [
        "/_layout/study-plans/$studyPlanId/details/edit",
        "/_layout/study-plans/$studyPlanId/details/"
      ]
    },
    "/_layout/courses/$courseId/edit": {
      "filePath": "_layout/courses/$courseId/edit.tsx",
      "parent": "/_layout/courses/$courseId"
    },
    "/_layout/programs/$programId/edit": {
      "filePath": "_layout/programs/$programId/edit.tsx",
      "parent": "/_layout/programs/$programId"
    },
    "/_layout/study-plans/$studyPlanId/framework": {
      "filePath": "_layout/study-plans/$studyPlanId/framework.tsx",
      "parent": "/_layout/study-plans/$studyPlanId"
    },
    "/_layout/study-plans/$studyPlanId/program-map": {
      "filePath": "_layout/study-plans/$studyPlanId/program-map.tsx",
      "parent": "/_layout/study-plans/$studyPlanId"
    },
    "/_layout/courses/$courseId/": {
      "filePath": "_layout/courses/$courseId/index.tsx",
      "parent": "/_layout/courses/$courseId"
    },
    "/_layout/programs/$programId/": {
      "filePath": "_layout/programs/$programId/index.tsx",
      "parent": "/_layout/programs/$programId"
    },
    "/_layout/study-plans/$studyPlanId/": {
      "filePath": "_layout/study-plans/$studyPlanId/index.tsx",
      "parent": "/_layout/study-plans/$studyPlanId"
    },
    "/_layout/study-plans/$studyPlanId/details/edit": {
      "filePath": "_layout/study-plans/$studyPlanId/details/edit.tsx",
      "parent": "/_layout/study-plans/$studyPlanId/details"
    },
    "/_layout/study-plans/$studyPlanId/sections/new": {
      "filePath": "_layout/study-plans/$studyPlanId/sections/new.tsx",
      "parent": "/_layout/study-plans/$studyPlanId"
    },
    "/_layout/study-plans/$studyPlanId/details/": {
      "filePath": "_layout/study-plans/$studyPlanId/details/index.tsx",
      "parent": "/_layout/study-plans/$studyPlanId/details"
    },
    "/_layout/study-plans/$studyPlanId/sections/": {
      "filePath": "_layout/study-plans/$studyPlanId/sections/index.tsx",
      "parent": "/_layout/study-plans/$studyPlanId"
    }
  }
}
ROUTE_MANIFEST_END */
