/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout/route'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutStudyPlansIndexImport } from './routes/_layout/study-plans/index'
import { Route as LayoutPublishesIndexImport } from './routes/_layout/publishes/index'
import { Route as LayoutProgramsIndexImport } from './routes/_layout/programs/index'
import { Route as LayoutCoursesIndexImport } from './routes/_layout/courses/index'
import { Route as LayoutStudyPlansNewImport } from './routes/_layout/study-plans/new'
import { Route as LayoutProgramsNewImport } from './routes/_layout/programs/new'
import { Route as LayoutCoursesNewImport } from './routes/_layout/courses/new'
import { Route as LayoutStudyPlansStudyPlanIdRouteImport } from './routes/_layout/study-plans/$studyPlanId/route'
import { Route as LayoutProgramsProgramIdIndexImport } from './routes/_layout/programs/$programId/index'
import { Route as LayoutCoursesCourseIdIndexImport } from './routes/_layout/courses/$courseId/index'
import { Route as LayoutStudyPlansStudyPlanIdProgramMapImport } from './routes/_layout/study-plans/$studyPlanId/program-map'
import { Route as LayoutStudyPlansStudyPlanIdCoursesImport } from './routes/_layout/study-plans/$studyPlanId/courses'
import { Route as LayoutProgramsProgramIdEditImport } from './routes/_layout/programs/$programId/edit'
import { Route as LayoutCoursesCourseIdEditImport } from './routes/_layout/courses/$courseId/edit'
import { Route as LayoutStudyPlansStudyPlanIdSectionsIndexImport } from './routes/_layout/study-plans/$studyPlanId/sections/index'
import { Route as LayoutStudyPlansStudyPlanIdDetailsIndexImport } from './routes/_layout/study-plans/$studyPlanId/details/index'
import { Route as LayoutStudyPlansStudyPlanIdSectionsNewImport } from './routes/_layout/study-plans/$studyPlanId/sections/new'
import { Route as LayoutStudyPlansStudyPlanIdDetailsEditImport } from './routes/_layout/study-plans/$studyPlanId/details/edit'
import { Route as LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexImport } from './routes/_layout/study-plans/$studyPlanId/sections/$sectionId/index'
import { Route as LayoutStudyPlansStudyPlanIdSectionsSectionIdEditImport } from './routes/_layout/study-plans/$studyPlanId/sections/$sectionId/edit'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRouteRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutStudyPlansIndexRoute = LayoutStudyPlansIndexImport.update({
  id: '/study-plans/',
  path: '/study-plans/',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutPublishesIndexRoute = LayoutPublishesIndexImport.update({
  id: '/publishes/',
  path: '/publishes/',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutProgramsIndexRoute = LayoutProgramsIndexImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutCoursesIndexRoute = LayoutCoursesIndexImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutStudyPlansNewRoute = LayoutStudyPlansNewImport.update({
  id: '/study-plans/new',
  path: '/study-plans/new',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutProgramsNewRoute = LayoutProgramsNewImport.update({
  id: '/programs/new',
  path: '/programs/new',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutCoursesNewRoute = LayoutCoursesNewImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutStudyPlansStudyPlanIdRouteRoute =
  LayoutStudyPlansStudyPlanIdRouteImport.update({
    id: '/study-plans/$studyPlanId',
    path: '/study-plans/$studyPlanId',
    getParentRoute: () => LayoutRouteRoute,
  } as any)

const LayoutProgramsProgramIdIndexRoute =
  LayoutProgramsProgramIdIndexImport.update({
    id: '/programs/$programId/',
    path: '/programs/$programId/',
    getParentRoute: () => LayoutRouteRoute,
  } as any)

const LayoutCoursesCourseIdIndexRoute = LayoutCoursesCourseIdIndexImport.update(
  {
    id: '/courses/$courseId/',
    path: '/courses/$courseId/',
    getParentRoute: () => LayoutRouteRoute,
  } as any,
)

const LayoutStudyPlansStudyPlanIdProgramMapRoute =
  LayoutStudyPlansStudyPlanIdProgramMapImport.update({
    id: '/program-map',
    path: '/program-map',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

const LayoutStudyPlansStudyPlanIdCoursesRoute =
  LayoutStudyPlansStudyPlanIdCoursesImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

const LayoutProgramsProgramIdEditRoute =
  LayoutProgramsProgramIdEditImport.update({
    id: '/programs/$programId/edit',
    path: '/programs/$programId/edit',
    getParentRoute: () => LayoutRouteRoute,
  } as any)

const LayoutCoursesCourseIdEditRoute = LayoutCoursesCourseIdEditImport.update({
  id: '/courses/$courseId/edit',
  path: '/courses/$courseId/edit',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutStudyPlansStudyPlanIdSectionsIndexRoute =
  LayoutStudyPlansStudyPlanIdSectionsIndexImport.update({
    id: '/sections/',
    path: '/sections/',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

const LayoutStudyPlansStudyPlanIdDetailsIndexRoute =
  LayoutStudyPlansStudyPlanIdDetailsIndexImport.update({
    id: '/details/',
    path: '/details/',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

const LayoutStudyPlansStudyPlanIdSectionsNewRoute =
  LayoutStudyPlansStudyPlanIdSectionsNewImport.update({
    id: '/sections/new',
    path: '/sections/new',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

const LayoutStudyPlansStudyPlanIdDetailsEditRoute =
  LayoutStudyPlansStudyPlanIdDetailsEditImport.update({
    id: '/details/edit',
    path: '/details/edit',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

const LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRoute =
  LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexImport.update({
    id: '/sections/$sectionId/',
    path: '/sections/$sectionId/',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

const LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRoute =
  LayoutStudyPlansStudyPlanIdSectionsSectionIdEditImport.update({
    id: '/sections/$sectionId/edit',
    path: '/sections/$sectionId/edit',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_layout/study-plans/$studyPlanId': {
      id: '/_layout/study-plans/$studyPlanId'
      path: '/study-plans/$studyPlanId'
      fullPath: '/study-plans/$studyPlanId'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/courses/new': {
      id: '/_layout/courses/new'
      path: '/courses/new'
      fullPath: '/courses/new'
      preLoaderRoute: typeof LayoutCoursesNewImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/programs/new': {
      id: '/_layout/programs/new'
      path: '/programs/new'
      fullPath: '/programs/new'
      preLoaderRoute: typeof LayoutProgramsNewImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/study-plans/new': {
      id: '/_layout/study-plans/new'
      path: '/study-plans/new'
      fullPath: '/study-plans/new'
      preLoaderRoute: typeof LayoutStudyPlansNewImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/courses/': {
      id: '/_layout/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof LayoutCoursesIndexImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/programs/': {
      id: '/_layout/programs/'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof LayoutProgramsIndexImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/publishes/': {
      id: '/_layout/publishes/'
      path: '/publishes'
      fullPath: '/publishes'
      preLoaderRoute: typeof LayoutPublishesIndexImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/study-plans/': {
      id: '/_layout/study-plans/'
      path: '/study-plans'
      fullPath: '/study-plans'
      preLoaderRoute: typeof LayoutStudyPlansIndexImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/courses/$courseId/edit': {
      id: '/_layout/courses/$courseId/edit'
      path: '/courses/$courseId/edit'
      fullPath: '/courses/$courseId/edit'
      preLoaderRoute: typeof LayoutCoursesCourseIdEditImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/programs/$programId/edit': {
      id: '/_layout/programs/$programId/edit'
      path: '/programs/$programId/edit'
      fullPath: '/programs/$programId/edit'
      preLoaderRoute: typeof LayoutProgramsProgramIdEditImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/study-plans/$studyPlanId/courses': {
      id: '/_layout/study-plans/$studyPlanId/courses'
      path: '/courses'
      fullPath: '/study-plans/$studyPlanId/courses'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdCoursesImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
    '/_layout/study-plans/$studyPlanId/program-map': {
      id: '/_layout/study-plans/$studyPlanId/program-map'
      path: '/program-map'
      fullPath: '/study-plans/$studyPlanId/program-map'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdProgramMapImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
    '/_layout/courses/$courseId/': {
      id: '/_layout/courses/$courseId/'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof LayoutCoursesCourseIdIndexImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/programs/$programId/': {
      id: '/_layout/programs/$programId/'
      path: '/programs/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof LayoutProgramsProgramIdIndexImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/study-plans/$studyPlanId/details/edit': {
      id: '/_layout/study-plans/$studyPlanId/details/edit'
      path: '/details/edit'
      fullPath: '/study-plans/$studyPlanId/details/edit'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdDetailsEditImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
    '/_layout/study-plans/$studyPlanId/sections/new': {
      id: '/_layout/study-plans/$studyPlanId/sections/new'
      path: '/sections/new'
      fullPath: '/study-plans/$studyPlanId/sections/new'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdSectionsNewImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
    '/_layout/study-plans/$studyPlanId/details/': {
      id: '/_layout/study-plans/$studyPlanId/details/'
      path: '/details'
      fullPath: '/study-plans/$studyPlanId/details'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdDetailsIndexImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
    '/_layout/study-plans/$studyPlanId/sections/': {
      id: '/_layout/study-plans/$studyPlanId/sections/'
      path: '/sections'
      fullPath: '/study-plans/$studyPlanId/sections'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdSectionsIndexImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
    '/_layout/study-plans/$studyPlanId/sections/$sectionId/edit': {
      id: '/_layout/study-plans/$studyPlanId/sections/$sectionId/edit'
      path: '/sections/$sectionId/edit'
      fullPath: '/study-plans/$studyPlanId/sections/$sectionId/edit'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdEditImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
    '/_layout/study-plans/$studyPlanId/sections/$sectionId/': {
      id: '/_layout/study-plans/$studyPlanId/sections/$sectionId/'
      path: '/sections/$sectionId'
      fullPath: '/study-plans/$studyPlanId/sections/$sectionId'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
  }
}

// Create and export the route tree

interface LayoutStudyPlansStudyPlanIdRouteRouteChildren {
  LayoutStudyPlansStudyPlanIdCoursesRoute: typeof LayoutStudyPlansStudyPlanIdCoursesRoute
  LayoutStudyPlansStudyPlanIdProgramMapRoute: typeof LayoutStudyPlansStudyPlanIdProgramMapRoute
  LayoutStudyPlansStudyPlanIdDetailsEditRoute: typeof LayoutStudyPlansStudyPlanIdDetailsEditRoute
  LayoutStudyPlansStudyPlanIdSectionsNewRoute: typeof LayoutStudyPlansStudyPlanIdSectionsNewRoute
  LayoutStudyPlansStudyPlanIdDetailsIndexRoute: typeof LayoutStudyPlansStudyPlanIdDetailsIndexRoute
  LayoutStudyPlansStudyPlanIdSectionsIndexRoute: typeof LayoutStudyPlansStudyPlanIdSectionsIndexRoute
  LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRoute: typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRoute
  LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRoute: typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRoute
}

const LayoutStudyPlansStudyPlanIdRouteRouteChildren: LayoutStudyPlansStudyPlanIdRouteRouteChildren =
  {
    LayoutStudyPlansStudyPlanIdCoursesRoute:
      LayoutStudyPlansStudyPlanIdCoursesRoute,
    LayoutStudyPlansStudyPlanIdProgramMapRoute:
      LayoutStudyPlansStudyPlanIdProgramMapRoute,
    LayoutStudyPlansStudyPlanIdDetailsEditRoute:
      LayoutStudyPlansStudyPlanIdDetailsEditRoute,
    LayoutStudyPlansStudyPlanIdSectionsNewRoute:
      LayoutStudyPlansStudyPlanIdSectionsNewRoute,
    LayoutStudyPlansStudyPlanIdDetailsIndexRoute:
      LayoutStudyPlansStudyPlanIdDetailsIndexRoute,
    LayoutStudyPlansStudyPlanIdSectionsIndexRoute:
      LayoutStudyPlansStudyPlanIdSectionsIndexRoute,
    LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRoute:
      LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRoute,
    LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRoute:
      LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRoute,
  }

const LayoutStudyPlansStudyPlanIdRouteRouteWithChildren =
  LayoutStudyPlansStudyPlanIdRouteRoute._addFileChildren(
    LayoutStudyPlansStudyPlanIdRouteRouteChildren,
  )

interface LayoutRouteRouteChildren {
  LayoutStudyPlansStudyPlanIdRouteRoute: typeof LayoutStudyPlansStudyPlanIdRouteRouteWithChildren
  LayoutCoursesNewRoute: typeof LayoutCoursesNewRoute
  LayoutProgramsNewRoute: typeof LayoutProgramsNewRoute
  LayoutStudyPlansNewRoute: typeof LayoutStudyPlansNewRoute
  LayoutCoursesIndexRoute: typeof LayoutCoursesIndexRoute
  LayoutProgramsIndexRoute: typeof LayoutProgramsIndexRoute
  LayoutPublishesIndexRoute: typeof LayoutPublishesIndexRoute
  LayoutStudyPlansIndexRoute: typeof LayoutStudyPlansIndexRoute
  LayoutCoursesCourseIdEditRoute: typeof LayoutCoursesCourseIdEditRoute
  LayoutProgramsProgramIdEditRoute: typeof LayoutProgramsProgramIdEditRoute
  LayoutCoursesCourseIdIndexRoute: typeof LayoutCoursesCourseIdIndexRoute
  LayoutProgramsProgramIdIndexRoute: typeof LayoutProgramsProgramIdIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutStudyPlansStudyPlanIdRouteRoute:
    LayoutStudyPlansStudyPlanIdRouteRouteWithChildren,
  LayoutCoursesNewRoute: LayoutCoursesNewRoute,
  LayoutProgramsNewRoute: LayoutProgramsNewRoute,
  LayoutStudyPlansNewRoute: LayoutStudyPlansNewRoute,
  LayoutCoursesIndexRoute: LayoutCoursesIndexRoute,
  LayoutProgramsIndexRoute: LayoutProgramsIndexRoute,
  LayoutPublishesIndexRoute: LayoutPublishesIndexRoute,
  LayoutStudyPlansIndexRoute: LayoutStudyPlansIndexRoute,
  LayoutCoursesCourseIdEditRoute: LayoutCoursesCourseIdEditRoute,
  LayoutProgramsProgramIdEditRoute: LayoutProgramsProgramIdEditRoute,
  LayoutCoursesCourseIdIndexRoute: LayoutCoursesCourseIdIndexRoute,
  LayoutProgramsProgramIdIndexRoute: LayoutProgramsProgramIdIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/study-plans/$studyPlanId': typeof LayoutStudyPlansStudyPlanIdRouteRouteWithChildren
  '/courses/new': typeof LayoutCoursesNewRoute
  '/programs/new': typeof LayoutProgramsNewRoute
  '/study-plans/new': typeof LayoutStudyPlansNewRoute
  '/courses': typeof LayoutCoursesIndexRoute
  '/programs': typeof LayoutProgramsIndexRoute
  '/publishes': typeof LayoutPublishesIndexRoute
  '/study-plans': typeof LayoutStudyPlansIndexRoute
  '/courses/$courseId/edit': typeof LayoutCoursesCourseIdEditRoute
  '/programs/$programId/edit': typeof LayoutProgramsProgramIdEditRoute
  '/study-plans/$studyPlanId/courses': typeof LayoutStudyPlansStudyPlanIdCoursesRoute
  '/study-plans/$studyPlanId/program-map': typeof LayoutStudyPlansStudyPlanIdProgramMapRoute
  '/courses/$courseId': typeof LayoutCoursesCourseIdIndexRoute
  '/programs/$programId': typeof LayoutProgramsProgramIdIndexRoute
  '/study-plans/$studyPlanId/details/edit': typeof LayoutStudyPlansStudyPlanIdDetailsEditRoute
  '/study-plans/$studyPlanId/sections/new': typeof LayoutStudyPlansStudyPlanIdSectionsNewRoute
  '/study-plans/$studyPlanId/details': typeof LayoutStudyPlansStudyPlanIdDetailsIndexRoute
  '/study-plans/$studyPlanId/sections': typeof LayoutStudyPlansStudyPlanIdSectionsIndexRoute
  '/study-plans/$studyPlanId/sections/$sectionId/edit': typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRoute
  '/study-plans/$studyPlanId/sections/$sectionId': typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/study-plans/$studyPlanId': typeof LayoutStudyPlansStudyPlanIdRouteRouteWithChildren
  '/courses/new': typeof LayoutCoursesNewRoute
  '/programs/new': typeof LayoutProgramsNewRoute
  '/study-plans/new': typeof LayoutStudyPlansNewRoute
  '/courses': typeof LayoutCoursesIndexRoute
  '/programs': typeof LayoutProgramsIndexRoute
  '/publishes': typeof LayoutPublishesIndexRoute
  '/study-plans': typeof LayoutStudyPlansIndexRoute
  '/courses/$courseId/edit': typeof LayoutCoursesCourseIdEditRoute
  '/programs/$programId/edit': typeof LayoutProgramsProgramIdEditRoute
  '/study-plans/$studyPlanId/courses': typeof LayoutStudyPlansStudyPlanIdCoursesRoute
  '/study-plans/$studyPlanId/program-map': typeof LayoutStudyPlansStudyPlanIdProgramMapRoute
  '/courses/$courseId': typeof LayoutCoursesCourseIdIndexRoute
  '/programs/$programId': typeof LayoutProgramsProgramIdIndexRoute
  '/study-plans/$studyPlanId/details/edit': typeof LayoutStudyPlansStudyPlanIdDetailsEditRoute
  '/study-plans/$studyPlanId/sections/new': typeof LayoutStudyPlansStudyPlanIdSectionsNewRoute
  '/study-plans/$studyPlanId/details': typeof LayoutStudyPlansStudyPlanIdDetailsIndexRoute
  '/study-plans/$studyPlanId/sections': typeof LayoutStudyPlansStudyPlanIdSectionsIndexRoute
  '/study-plans/$studyPlanId/sections/$sectionId/edit': typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRoute
  '/study-plans/$studyPlanId/sections/$sectionId': typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/study-plans/$studyPlanId': typeof LayoutStudyPlansStudyPlanIdRouteRouteWithChildren
  '/_layout/courses/new': typeof LayoutCoursesNewRoute
  '/_layout/programs/new': typeof LayoutProgramsNewRoute
  '/_layout/study-plans/new': typeof LayoutStudyPlansNewRoute
  '/_layout/courses/': typeof LayoutCoursesIndexRoute
  '/_layout/programs/': typeof LayoutProgramsIndexRoute
  '/_layout/publishes/': typeof LayoutPublishesIndexRoute
  '/_layout/study-plans/': typeof LayoutStudyPlansIndexRoute
  '/_layout/courses/$courseId/edit': typeof LayoutCoursesCourseIdEditRoute
  '/_layout/programs/$programId/edit': typeof LayoutProgramsProgramIdEditRoute
  '/_layout/study-plans/$studyPlanId/courses': typeof LayoutStudyPlansStudyPlanIdCoursesRoute
  '/_layout/study-plans/$studyPlanId/program-map': typeof LayoutStudyPlansStudyPlanIdProgramMapRoute
  '/_layout/courses/$courseId/': typeof LayoutCoursesCourseIdIndexRoute
  '/_layout/programs/$programId/': typeof LayoutProgramsProgramIdIndexRoute
  '/_layout/study-plans/$studyPlanId/details/edit': typeof LayoutStudyPlansStudyPlanIdDetailsEditRoute
  '/_layout/study-plans/$studyPlanId/sections/new': typeof LayoutStudyPlansStudyPlanIdSectionsNewRoute
  '/_layout/study-plans/$studyPlanId/details/': typeof LayoutStudyPlansStudyPlanIdDetailsIndexRoute
  '/_layout/study-plans/$studyPlanId/sections/': typeof LayoutStudyPlansStudyPlanIdSectionsIndexRoute
  '/_layout/study-plans/$studyPlanId/sections/$sectionId/edit': typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRoute
  '/_layout/study-plans/$studyPlanId/sections/$sectionId/': typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/study-plans/$studyPlanId'
    | '/courses/new'
    | '/programs/new'
    | '/study-plans/new'
    | '/courses'
    | '/programs'
    | '/publishes'
    | '/study-plans'
    | '/courses/$courseId/edit'
    | '/programs/$programId/edit'
    | '/study-plans/$studyPlanId/courses'
    | '/study-plans/$studyPlanId/program-map'
    | '/courses/$courseId'
    | '/programs/$programId'
    | '/study-plans/$studyPlanId/details/edit'
    | '/study-plans/$studyPlanId/sections/new'
    | '/study-plans/$studyPlanId/details'
    | '/study-plans/$studyPlanId/sections'
    | '/study-plans/$studyPlanId/sections/$sectionId/edit'
    | '/study-plans/$studyPlanId/sections/$sectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/study-plans/$studyPlanId'
    | '/courses/new'
    | '/programs/new'
    | '/study-plans/new'
    | '/courses'
    | '/programs'
    | '/publishes'
    | '/study-plans'
    | '/courses/$courseId/edit'
    | '/programs/$programId/edit'
    | '/study-plans/$studyPlanId/courses'
    | '/study-plans/$studyPlanId/program-map'
    | '/courses/$courseId'
    | '/programs/$programId'
    | '/study-plans/$studyPlanId/details/edit'
    | '/study-plans/$studyPlanId/sections/new'
    | '/study-plans/$studyPlanId/details'
    | '/study-plans/$studyPlanId/sections'
    | '/study-plans/$studyPlanId/sections/$sectionId/edit'
    | '/study-plans/$studyPlanId/sections/$sectionId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/_layout/study-plans/$studyPlanId'
    | '/_layout/courses/new'
    | '/_layout/programs/new'
    | '/_layout/study-plans/new'
    | '/_layout/courses/'
    | '/_layout/programs/'
    | '/_layout/publishes/'
    | '/_layout/study-plans/'
    | '/_layout/courses/$courseId/edit'
    | '/_layout/programs/$programId/edit'
    | '/_layout/study-plans/$studyPlanId/courses'
    | '/_layout/study-plans/$studyPlanId/program-map'
    | '/_layout/courses/$courseId/'
    | '/_layout/programs/$programId/'
    | '/_layout/study-plans/$studyPlanId/details/edit'
    | '/_layout/study-plans/$studyPlanId/sections/new'
    | '/_layout/study-plans/$studyPlanId/details/'
    | '/_layout/study-plans/$studyPlanId/sections/'
    | '/_layout/study-plans/$studyPlanId/sections/$sectionId/edit'
    | '/_layout/study-plans/$studyPlanId/sections/$sectionId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout/route.tsx",
      "children": [
        "/_layout/study-plans/$studyPlanId",
        "/_layout/courses/new",
        "/_layout/programs/new",
        "/_layout/study-plans/new",
        "/_layout/courses/",
        "/_layout/programs/",
        "/_layout/publishes/",
        "/_layout/study-plans/",
        "/_layout/courses/$courseId/edit",
        "/_layout/programs/$programId/edit",
        "/_layout/courses/$courseId/",
        "/_layout/programs/$programId/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_layout/study-plans/$studyPlanId": {
      "filePath": "_layout/study-plans/$studyPlanId/route.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/study-plans/$studyPlanId/courses",
        "/_layout/study-plans/$studyPlanId/program-map",
        "/_layout/study-plans/$studyPlanId/details/edit",
        "/_layout/study-plans/$studyPlanId/sections/new",
        "/_layout/study-plans/$studyPlanId/details/",
        "/_layout/study-plans/$studyPlanId/sections/",
        "/_layout/study-plans/$studyPlanId/sections/$sectionId/edit",
        "/_layout/study-plans/$studyPlanId/sections/$sectionId/"
      ]
    },
    "/_layout/courses/new": {
      "filePath": "_layout/courses/new.tsx",
      "parent": "/_layout"
    },
    "/_layout/programs/new": {
      "filePath": "_layout/programs/new.tsx",
      "parent": "/_layout"
    },
    "/_layout/study-plans/new": {
      "filePath": "_layout/study-plans/new.tsx",
      "parent": "/_layout"
    },
    "/_layout/courses/": {
      "filePath": "_layout/courses/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/programs/": {
      "filePath": "_layout/programs/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/publishes/": {
      "filePath": "_layout/publishes/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/study-plans/": {
      "filePath": "_layout/study-plans/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/courses/$courseId/edit": {
      "filePath": "_layout/courses/$courseId/edit.tsx",
      "parent": "/_layout"
    },
    "/_layout/programs/$programId/edit": {
      "filePath": "_layout/programs/$programId/edit.tsx",
      "parent": "/_layout"
    },
    "/_layout/study-plans/$studyPlanId/courses": {
      "filePath": "_layout/study-plans/$studyPlanId/courses.tsx",
      "parent": "/_layout/study-plans/$studyPlanId"
    },
    "/_layout/study-plans/$studyPlanId/program-map": {
      "filePath": "_layout/study-plans/$studyPlanId/program-map.tsx",
      "parent": "/_layout/study-plans/$studyPlanId"
    },
    "/_layout/courses/$courseId/": {
      "filePath": "_layout/courses/$courseId/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/programs/$programId/": {
      "filePath": "_layout/programs/$programId/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/study-plans/$studyPlanId/details/edit": {
      "filePath": "_layout/study-plans/$studyPlanId/details/edit.tsx",
      "parent": "/_layout/study-plans/$studyPlanId"
    },
    "/_layout/study-plans/$studyPlanId/sections/new": {
      "filePath": "_layout/study-plans/$studyPlanId/sections/new.tsx",
      "parent": "/_layout/study-plans/$studyPlanId"
    },
    "/_layout/study-plans/$studyPlanId/details/": {
      "filePath": "_layout/study-plans/$studyPlanId/details/index.tsx",
      "parent": "/_layout/study-plans/$studyPlanId"
    },
    "/_layout/study-plans/$studyPlanId/sections/": {
      "filePath": "_layout/study-plans/$studyPlanId/sections/index.tsx",
      "parent": "/_layout/study-plans/$studyPlanId"
    },
    "/_layout/study-plans/$studyPlanId/sections/$sectionId/edit": {
      "filePath": "_layout/study-plans/$studyPlanId/sections/$sectionId/edit.tsx",
      "parent": "/_layout/study-plans/$studyPlanId"
    },
    "/_layout/study-plans/$studyPlanId/sections/$sectionId/": {
      "filePath": "_layout/study-plans/$studyPlanId/sections/$sectionId/index.tsx",
      "parent": "/_layout/study-plans/$studyPlanId"
    }
  }
}
ROUTE_MANIFEST_END */
