/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout/route'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutCatalogRouteImport } from './routes/_layout/catalog/route'
import { Route as LayoutUsersIndexImport } from './routes/_layout/users/index'
import { Route as LayoutStudyPlansIndexImport } from './routes/_layout/study-plans/index'
import { Route as LayoutCatalogIndexImport } from './routes/_layout/catalog/index'
import { Route as LayoutUsersNewImport } from './routes/_layout/users/new'
import { Route as LayoutStudyPlansNewImport } from './routes/_layout/study-plans/new'
import { Route as LayoutStudyPlansStudyPlanIdRouteImport } from './routes/_layout/study-plans/$studyPlanId/route'
import { Route as LayoutCatalogProgramsIndexImport } from './routes/_layout/catalog/programs/index'
import { Route as LayoutCatalogCoursesIndexImport } from './routes/_layout/catalog/courses/index'
import { Route as LayoutStudyPlansStudyPlanIdProgramMapImport } from './routes/_layout/study-plans/$studyPlanId/program-map'
import { Route as LayoutStudyPlansStudyPlanIdCoursesImport } from './routes/_layout/study-plans/$studyPlanId/courses'
import { Route as LayoutCatalogProgramsNewImport } from './routes/_layout/catalog/programs/new'
import { Route as LayoutCatalogCoursesNewImport } from './routes/_layout/catalog/courses/new'
import { Route as LayoutStudyPlansStudyPlanIdSectionsIndexImport } from './routes/_layout/study-plans/$studyPlanId/sections/index'
import { Route as LayoutStudyPlansStudyPlanIdDetailsIndexImport } from './routes/_layout/study-plans/$studyPlanId/details/index'
import { Route as LayoutCatalogProgramsProgramIdIndexImport } from './routes/_layout/catalog/programs/$programId/index'
import { Route as LayoutCatalogCoursesCourseIdIndexImport } from './routes/_layout/catalog/courses/$courseId/index'
import { Route as LayoutStudyPlansStudyPlanIdSectionsNewImport } from './routes/_layout/study-plans/$studyPlanId/sections/new'
import { Route as LayoutStudyPlansStudyPlanIdDetailsEditImport } from './routes/_layout/study-plans/$studyPlanId/details/edit'
import { Route as LayoutCatalogProgramsProgramIdEditImport } from './routes/_layout/catalog/programs/$programId/edit'
import { Route as LayoutCatalogCoursesCourseIdEditImport } from './routes/_layout/catalog/courses/$courseId/edit'
import { Route as LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexImport } from './routes/_layout/study-plans/$studyPlanId/sections/$sectionId/index'
import { Route as LayoutStudyPlansStudyPlanIdSectionsSectionIdEditImport } from './routes/_layout/study-plans/$studyPlanId/sections/$sectionId/edit'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRouteRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutCatalogRouteRoute = LayoutCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutUsersIndexRoute = LayoutUsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutStudyPlansIndexRoute = LayoutStudyPlansIndexImport.update({
  id: '/study-plans/',
  path: '/study-plans/',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutCatalogIndexRoute = LayoutCatalogIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutCatalogRouteRoute,
} as any)

const LayoutUsersNewRoute = LayoutUsersNewImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutStudyPlansNewRoute = LayoutStudyPlansNewImport.update({
  id: '/study-plans/new',
  path: '/study-plans/new',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutStudyPlansStudyPlanIdRouteRoute =
  LayoutStudyPlansStudyPlanIdRouteImport.update({
    id: '/study-plans/$studyPlanId',
    path: '/study-plans/$studyPlanId',
    getParentRoute: () => LayoutRouteRoute,
  } as any)

const LayoutCatalogProgramsIndexRoute = LayoutCatalogProgramsIndexImport.update(
  {
    id: '/programs/',
    path: '/programs/',
    getParentRoute: () => LayoutCatalogRouteRoute,
  } as any,
)

const LayoutCatalogCoursesIndexRoute = LayoutCatalogCoursesIndexImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => LayoutCatalogRouteRoute,
} as any)

const LayoutStudyPlansStudyPlanIdProgramMapRoute =
  LayoutStudyPlansStudyPlanIdProgramMapImport.update({
    id: '/program-map',
    path: '/program-map',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

const LayoutStudyPlansStudyPlanIdCoursesRoute =
  LayoutStudyPlansStudyPlanIdCoursesImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

const LayoutCatalogProgramsNewRoute = LayoutCatalogProgramsNewImport.update({
  id: '/programs/new',
  path: '/programs/new',
  getParentRoute: () => LayoutCatalogRouteRoute,
} as any)

const LayoutCatalogCoursesNewRoute = LayoutCatalogCoursesNewImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => LayoutCatalogRouteRoute,
} as any)

const LayoutStudyPlansStudyPlanIdSectionsIndexRoute =
  LayoutStudyPlansStudyPlanIdSectionsIndexImport.update({
    id: '/sections/',
    path: '/sections/',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

const LayoutStudyPlansStudyPlanIdDetailsIndexRoute =
  LayoutStudyPlansStudyPlanIdDetailsIndexImport.update({
    id: '/details/',
    path: '/details/',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

const LayoutCatalogProgramsProgramIdIndexRoute =
  LayoutCatalogProgramsProgramIdIndexImport.update({
    id: '/programs/$programId/',
    path: '/programs/$programId/',
    getParentRoute: () => LayoutCatalogRouteRoute,
  } as any)

const LayoutCatalogCoursesCourseIdIndexRoute =
  LayoutCatalogCoursesCourseIdIndexImport.update({
    id: '/courses/$courseId/',
    path: '/courses/$courseId/',
    getParentRoute: () => LayoutCatalogRouteRoute,
  } as any)

const LayoutStudyPlansStudyPlanIdSectionsNewRoute =
  LayoutStudyPlansStudyPlanIdSectionsNewImport.update({
    id: '/sections/new',
    path: '/sections/new',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

const LayoutStudyPlansStudyPlanIdDetailsEditRoute =
  LayoutStudyPlansStudyPlanIdDetailsEditImport.update({
    id: '/details/edit',
    path: '/details/edit',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

const LayoutCatalogProgramsProgramIdEditRoute =
  LayoutCatalogProgramsProgramIdEditImport.update({
    id: '/programs/$programId/edit',
    path: '/programs/$programId/edit',
    getParentRoute: () => LayoutCatalogRouteRoute,
  } as any)

const LayoutCatalogCoursesCourseIdEditRoute =
  LayoutCatalogCoursesCourseIdEditImport.update({
    id: '/courses/$courseId/edit',
    path: '/courses/$courseId/edit',
    getParentRoute: () => LayoutCatalogRouteRoute,
  } as any)

const LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRoute =
  LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexImport.update({
    id: '/sections/$sectionId/',
    path: '/sections/$sectionId/',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

const LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRoute =
  LayoutStudyPlansStudyPlanIdSectionsSectionIdEditImport.update({
    id: '/sections/$sectionId/edit',
    path: '/sections/$sectionId/edit',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_layout/catalog': {
      id: '/_layout/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof LayoutCatalogRouteImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/study-plans/$studyPlanId': {
      id: '/_layout/study-plans/$studyPlanId'
      path: '/study-plans/$studyPlanId'
      fullPath: '/study-plans/$studyPlanId'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/study-plans/new': {
      id: '/_layout/study-plans/new'
      path: '/study-plans/new'
      fullPath: '/study-plans/new'
      preLoaderRoute: typeof LayoutStudyPlansNewImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/users/new': {
      id: '/_layout/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof LayoutUsersNewImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/catalog/': {
      id: '/_layout/catalog/'
      path: '/'
      fullPath: '/catalog/'
      preLoaderRoute: typeof LayoutCatalogIndexImport
      parentRoute: typeof LayoutCatalogRouteImport
    }
    '/_layout/study-plans/': {
      id: '/_layout/study-plans/'
      path: '/study-plans'
      fullPath: '/study-plans'
      preLoaderRoute: typeof LayoutStudyPlansIndexImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/users/': {
      id: '/_layout/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersIndexImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/catalog/courses/new': {
      id: '/_layout/catalog/courses/new'
      path: '/courses/new'
      fullPath: '/catalog/courses/new'
      preLoaderRoute: typeof LayoutCatalogCoursesNewImport
      parentRoute: typeof LayoutCatalogRouteImport
    }
    '/_layout/catalog/programs/new': {
      id: '/_layout/catalog/programs/new'
      path: '/programs/new'
      fullPath: '/catalog/programs/new'
      preLoaderRoute: typeof LayoutCatalogProgramsNewImport
      parentRoute: typeof LayoutCatalogRouteImport
    }
    '/_layout/study-plans/$studyPlanId/courses': {
      id: '/_layout/study-plans/$studyPlanId/courses'
      path: '/courses'
      fullPath: '/study-plans/$studyPlanId/courses'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdCoursesImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
    '/_layout/study-plans/$studyPlanId/program-map': {
      id: '/_layout/study-plans/$studyPlanId/program-map'
      path: '/program-map'
      fullPath: '/study-plans/$studyPlanId/program-map'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdProgramMapImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
    '/_layout/catalog/courses/': {
      id: '/_layout/catalog/courses/'
      path: '/courses'
      fullPath: '/catalog/courses'
      preLoaderRoute: typeof LayoutCatalogCoursesIndexImport
      parentRoute: typeof LayoutCatalogRouteImport
    }
    '/_layout/catalog/programs/': {
      id: '/_layout/catalog/programs/'
      path: '/programs'
      fullPath: '/catalog/programs'
      preLoaderRoute: typeof LayoutCatalogProgramsIndexImport
      parentRoute: typeof LayoutCatalogRouteImport
    }
    '/_layout/catalog/courses/$courseId/edit': {
      id: '/_layout/catalog/courses/$courseId/edit'
      path: '/courses/$courseId/edit'
      fullPath: '/catalog/courses/$courseId/edit'
      preLoaderRoute: typeof LayoutCatalogCoursesCourseIdEditImport
      parentRoute: typeof LayoutCatalogRouteImport
    }
    '/_layout/catalog/programs/$programId/edit': {
      id: '/_layout/catalog/programs/$programId/edit'
      path: '/programs/$programId/edit'
      fullPath: '/catalog/programs/$programId/edit'
      preLoaderRoute: typeof LayoutCatalogProgramsProgramIdEditImport
      parentRoute: typeof LayoutCatalogRouteImport
    }
    '/_layout/study-plans/$studyPlanId/details/edit': {
      id: '/_layout/study-plans/$studyPlanId/details/edit'
      path: '/details/edit'
      fullPath: '/study-plans/$studyPlanId/details/edit'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdDetailsEditImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
    '/_layout/study-plans/$studyPlanId/sections/new': {
      id: '/_layout/study-plans/$studyPlanId/sections/new'
      path: '/sections/new'
      fullPath: '/study-plans/$studyPlanId/sections/new'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdSectionsNewImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
    '/_layout/catalog/courses/$courseId/': {
      id: '/_layout/catalog/courses/$courseId/'
      path: '/courses/$courseId'
      fullPath: '/catalog/courses/$courseId'
      preLoaderRoute: typeof LayoutCatalogCoursesCourseIdIndexImport
      parentRoute: typeof LayoutCatalogRouteImport
    }
    '/_layout/catalog/programs/$programId/': {
      id: '/_layout/catalog/programs/$programId/'
      path: '/programs/$programId'
      fullPath: '/catalog/programs/$programId'
      preLoaderRoute: typeof LayoutCatalogProgramsProgramIdIndexImport
      parentRoute: typeof LayoutCatalogRouteImport
    }
    '/_layout/study-plans/$studyPlanId/details/': {
      id: '/_layout/study-plans/$studyPlanId/details/'
      path: '/details'
      fullPath: '/study-plans/$studyPlanId/details'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdDetailsIndexImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
    '/_layout/study-plans/$studyPlanId/sections/': {
      id: '/_layout/study-plans/$studyPlanId/sections/'
      path: '/sections'
      fullPath: '/study-plans/$studyPlanId/sections'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdSectionsIndexImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
    '/_layout/study-plans/$studyPlanId/sections/$sectionId/edit': {
      id: '/_layout/study-plans/$studyPlanId/sections/$sectionId/edit'
      path: '/sections/$sectionId/edit'
      fullPath: '/study-plans/$studyPlanId/sections/$sectionId/edit'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdEditImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
    '/_layout/study-plans/$studyPlanId/sections/$sectionId/': {
      id: '/_layout/study-plans/$studyPlanId/sections/$sectionId/'
      path: '/sections/$sectionId'
      fullPath: '/study-plans/$studyPlanId/sections/$sectionId'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
  }
}

// Create and export the route tree

interface LayoutCatalogRouteRouteChildren {
  LayoutCatalogIndexRoute: typeof LayoutCatalogIndexRoute
  LayoutCatalogCoursesNewRoute: typeof LayoutCatalogCoursesNewRoute
  LayoutCatalogProgramsNewRoute: typeof LayoutCatalogProgramsNewRoute
  LayoutCatalogCoursesIndexRoute: typeof LayoutCatalogCoursesIndexRoute
  LayoutCatalogProgramsIndexRoute: typeof LayoutCatalogProgramsIndexRoute
  LayoutCatalogCoursesCourseIdEditRoute: typeof LayoutCatalogCoursesCourseIdEditRoute
  LayoutCatalogProgramsProgramIdEditRoute: typeof LayoutCatalogProgramsProgramIdEditRoute
  LayoutCatalogCoursesCourseIdIndexRoute: typeof LayoutCatalogCoursesCourseIdIndexRoute
  LayoutCatalogProgramsProgramIdIndexRoute: typeof LayoutCatalogProgramsProgramIdIndexRoute
}

const LayoutCatalogRouteRouteChildren: LayoutCatalogRouteRouteChildren = {
  LayoutCatalogIndexRoute: LayoutCatalogIndexRoute,
  LayoutCatalogCoursesNewRoute: LayoutCatalogCoursesNewRoute,
  LayoutCatalogProgramsNewRoute: LayoutCatalogProgramsNewRoute,
  LayoutCatalogCoursesIndexRoute: LayoutCatalogCoursesIndexRoute,
  LayoutCatalogProgramsIndexRoute: LayoutCatalogProgramsIndexRoute,
  LayoutCatalogCoursesCourseIdEditRoute: LayoutCatalogCoursesCourseIdEditRoute,
  LayoutCatalogProgramsProgramIdEditRoute:
    LayoutCatalogProgramsProgramIdEditRoute,
  LayoutCatalogCoursesCourseIdIndexRoute:
    LayoutCatalogCoursesCourseIdIndexRoute,
  LayoutCatalogProgramsProgramIdIndexRoute:
    LayoutCatalogProgramsProgramIdIndexRoute,
}

const LayoutCatalogRouteRouteWithChildren =
  LayoutCatalogRouteRoute._addFileChildren(LayoutCatalogRouteRouteChildren)

interface LayoutStudyPlansStudyPlanIdRouteRouteChildren {
  LayoutStudyPlansStudyPlanIdCoursesRoute: typeof LayoutStudyPlansStudyPlanIdCoursesRoute
  LayoutStudyPlansStudyPlanIdProgramMapRoute: typeof LayoutStudyPlansStudyPlanIdProgramMapRoute
  LayoutStudyPlansStudyPlanIdDetailsEditRoute: typeof LayoutStudyPlansStudyPlanIdDetailsEditRoute
  LayoutStudyPlansStudyPlanIdSectionsNewRoute: typeof LayoutStudyPlansStudyPlanIdSectionsNewRoute
  LayoutStudyPlansStudyPlanIdDetailsIndexRoute: typeof LayoutStudyPlansStudyPlanIdDetailsIndexRoute
  LayoutStudyPlansStudyPlanIdSectionsIndexRoute: typeof LayoutStudyPlansStudyPlanIdSectionsIndexRoute
  LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRoute: typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRoute
  LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRoute: typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRoute
}

const LayoutStudyPlansStudyPlanIdRouteRouteChildren: LayoutStudyPlansStudyPlanIdRouteRouteChildren =
  {
    LayoutStudyPlansStudyPlanIdCoursesRoute:
      LayoutStudyPlansStudyPlanIdCoursesRoute,
    LayoutStudyPlansStudyPlanIdProgramMapRoute:
      LayoutStudyPlansStudyPlanIdProgramMapRoute,
    LayoutStudyPlansStudyPlanIdDetailsEditRoute:
      LayoutStudyPlansStudyPlanIdDetailsEditRoute,
    LayoutStudyPlansStudyPlanIdSectionsNewRoute:
      LayoutStudyPlansStudyPlanIdSectionsNewRoute,
    LayoutStudyPlansStudyPlanIdDetailsIndexRoute:
      LayoutStudyPlansStudyPlanIdDetailsIndexRoute,
    LayoutStudyPlansStudyPlanIdSectionsIndexRoute:
      LayoutStudyPlansStudyPlanIdSectionsIndexRoute,
    LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRoute:
      LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRoute,
    LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRoute:
      LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRoute,
  }

const LayoutStudyPlansStudyPlanIdRouteRouteWithChildren =
  LayoutStudyPlansStudyPlanIdRouteRoute._addFileChildren(
    LayoutStudyPlansStudyPlanIdRouteRouteChildren,
  )

interface LayoutRouteRouteChildren {
  LayoutCatalogRouteRoute: typeof LayoutCatalogRouteRouteWithChildren
  LayoutStudyPlansStudyPlanIdRouteRoute: typeof LayoutStudyPlansStudyPlanIdRouteRouteWithChildren
  LayoutStudyPlansNewRoute: typeof LayoutStudyPlansNewRoute
  LayoutUsersNewRoute: typeof LayoutUsersNewRoute
  LayoutStudyPlansIndexRoute: typeof LayoutStudyPlansIndexRoute
  LayoutUsersIndexRoute: typeof LayoutUsersIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutCatalogRouteRoute: LayoutCatalogRouteRouteWithChildren,
  LayoutStudyPlansStudyPlanIdRouteRoute:
    LayoutStudyPlansStudyPlanIdRouteRouteWithChildren,
  LayoutStudyPlansNewRoute: LayoutStudyPlansNewRoute,
  LayoutUsersNewRoute: LayoutUsersNewRoute,
  LayoutStudyPlansIndexRoute: LayoutStudyPlansIndexRoute,
  LayoutUsersIndexRoute: LayoutUsersIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/catalog': typeof LayoutCatalogRouteRouteWithChildren
  '/study-plans/$studyPlanId': typeof LayoutStudyPlansStudyPlanIdRouteRouteWithChildren
  '/study-plans/new': typeof LayoutStudyPlansNewRoute
  '/users/new': typeof LayoutUsersNewRoute
  '/catalog/': typeof LayoutCatalogIndexRoute
  '/study-plans': typeof LayoutStudyPlansIndexRoute
  '/users': typeof LayoutUsersIndexRoute
  '/catalog/courses/new': typeof LayoutCatalogCoursesNewRoute
  '/catalog/programs/new': typeof LayoutCatalogProgramsNewRoute
  '/study-plans/$studyPlanId/courses': typeof LayoutStudyPlansStudyPlanIdCoursesRoute
  '/study-plans/$studyPlanId/program-map': typeof LayoutStudyPlansStudyPlanIdProgramMapRoute
  '/catalog/courses': typeof LayoutCatalogCoursesIndexRoute
  '/catalog/programs': typeof LayoutCatalogProgramsIndexRoute
  '/catalog/courses/$courseId/edit': typeof LayoutCatalogCoursesCourseIdEditRoute
  '/catalog/programs/$programId/edit': typeof LayoutCatalogProgramsProgramIdEditRoute
  '/study-plans/$studyPlanId/details/edit': typeof LayoutStudyPlansStudyPlanIdDetailsEditRoute
  '/study-plans/$studyPlanId/sections/new': typeof LayoutStudyPlansStudyPlanIdSectionsNewRoute
  '/catalog/courses/$courseId': typeof LayoutCatalogCoursesCourseIdIndexRoute
  '/catalog/programs/$programId': typeof LayoutCatalogProgramsProgramIdIndexRoute
  '/study-plans/$studyPlanId/details': typeof LayoutStudyPlansStudyPlanIdDetailsIndexRoute
  '/study-plans/$studyPlanId/sections': typeof LayoutStudyPlansStudyPlanIdSectionsIndexRoute
  '/study-plans/$studyPlanId/sections/$sectionId/edit': typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRoute
  '/study-plans/$studyPlanId/sections/$sectionId': typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/study-plans/$studyPlanId': typeof LayoutStudyPlansStudyPlanIdRouteRouteWithChildren
  '/study-plans/new': typeof LayoutStudyPlansNewRoute
  '/users/new': typeof LayoutUsersNewRoute
  '/catalog': typeof LayoutCatalogIndexRoute
  '/study-plans': typeof LayoutStudyPlansIndexRoute
  '/users': typeof LayoutUsersIndexRoute
  '/catalog/courses/new': typeof LayoutCatalogCoursesNewRoute
  '/catalog/programs/new': typeof LayoutCatalogProgramsNewRoute
  '/study-plans/$studyPlanId/courses': typeof LayoutStudyPlansStudyPlanIdCoursesRoute
  '/study-plans/$studyPlanId/program-map': typeof LayoutStudyPlansStudyPlanIdProgramMapRoute
  '/catalog/courses': typeof LayoutCatalogCoursesIndexRoute
  '/catalog/programs': typeof LayoutCatalogProgramsIndexRoute
  '/catalog/courses/$courseId/edit': typeof LayoutCatalogCoursesCourseIdEditRoute
  '/catalog/programs/$programId/edit': typeof LayoutCatalogProgramsProgramIdEditRoute
  '/study-plans/$studyPlanId/details/edit': typeof LayoutStudyPlansStudyPlanIdDetailsEditRoute
  '/study-plans/$studyPlanId/sections/new': typeof LayoutStudyPlansStudyPlanIdSectionsNewRoute
  '/catalog/courses/$courseId': typeof LayoutCatalogCoursesCourseIdIndexRoute
  '/catalog/programs/$programId': typeof LayoutCatalogProgramsProgramIdIndexRoute
  '/study-plans/$studyPlanId/details': typeof LayoutStudyPlansStudyPlanIdDetailsIndexRoute
  '/study-plans/$studyPlanId/sections': typeof LayoutStudyPlansStudyPlanIdSectionsIndexRoute
  '/study-plans/$studyPlanId/sections/$sectionId/edit': typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRoute
  '/study-plans/$studyPlanId/sections/$sectionId': typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/catalog': typeof LayoutCatalogRouteRouteWithChildren
  '/_layout/study-plans/$studyPlanId': typeof LayoutStudyPlansStudyPlanIdRouteRouteWithChildren
  '/_layout/study-plans/new': typeof LayoutStudyPlansNewRoute
  '/_layout/users/new': typeof LayoutUsersNewRoute
  '/_layout/catalog/': typeof LayoutCatalogIndexRoute
  '/_layout/study-plans/': typeof LayoutStudyPlansIndexRoute
  '/_layout/users/': typeof LayoutUsersIndexRoute
  '/_layout/catalog/courses/new': typeof LayoutCatalogCoursesNewRoute
  '/_layout/catalog/programs/new': typeof LayoutCatalogProgramsNewRoute
  '/_layout/study-plans/$studyPlanId/courses': typeof LayoutStudyPlansStudyPlanIdCoursesRoute
  '/_layout/study-plans/$studyPlanId/program-map': typeof LayoutStudyPlansStudyPlanIdProgramMapRoute
  '/_layout/catalog/courses/': typeof LayoutCatalogCoursesIndexRoute
  '/_layout/catalog/programs/': typeof LayoutCatalogProgramsIndexRoute
  '/_layout/catalog/courses/$courseId/edit': typeof LayoutCatalogCoursesCourseIdEditRoute
  '/_layout/catalog/programs/$programId/edit': typeof LayoutCatalogProgramsProgramIdEditRoute
  '/_layout/study-plans/$studyPlanId/details/edit': typeof LayoutStudyPlansStudyPlanIdDetailsEditRoute
  '/_layout/study-plans/$studyPlanId/sections/new': typeof LayoutStudyPlansStudyPlanIdSectionsNewRoute
  '/_layout/catalog/courses/$courseId/': typeof LayoutCatalogCoursesCourseIdIndexRoute
  '/_layout/catalog/programs/$programId/': typeof LayoutCatalogProgramsProgramIdIndexRoute
  '/_layout/study-plans/$studyPlanId/details/': typeof LayoutStudyPlansStudyPlanIdDetailsIndexRoute
  '/_layout/study-plans/$studyPlanId/sections/': typeof LayoutStudyPlansStudyPlanIdSectionsIndexRoute
  '/_layout/study-plans/$studyPlanId/sections/$sectionId/edit': typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdEditRoute
  '/_layout/study-plans/$studyPlanId/sections/$sectionId/': typeof LayoutStudyPlansStudyPlanIdSectionsSectionIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/catalog'
    | '/study-plans/$studyPlanId'
    | '/study-plans/new'
    | '/users/new'
    | '/catalog/'
    | '/study-plans'
    | '/users'
    | '/catalog/courses/new'
    | '/catalog/programs/new'
    | '/study-plans/$studyPlanId/courses'
    | '/study-plans/$studyPlanId/program-map'
    | '/catalog/courses'
    | '/catalog/programs'
    | '/catalog/courses/$courseId/edit'
    | '/catalog/programs/$programId/edit'
    | '/study-plans/$studyPlanId/details/edit'
    | '/study-plans/$studyPlanId/sections/new'
    | '/catalog/courses/$courseId'
    | '/catalog/programs/$programId'
    | '/study-plans/$studyPlanId/details'
    | '/study-plans/$studyPlanId/sections'
    | '/study-plans/$studyPlanId/sections/$sectionId/edit'
    | '/study-plans/$studyPlanId/sections/$sectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/study-plans/$studyPlanId'
    | '/study-plans/new'
    | '/users/new'
    | '/catalog'
    | '/study-plans'
    | '/users'
    | '/catalog/courses/new'
    | '/catalog/programs/new'
    | '/study-plans/$studyPlanId/courses'
    | '/study-plans/$studyPlanId/program-map'
    | '/catalog/courses'
    | '/catalog/programs'
    | '/catalog/courses/$courseId/edit'
    | '/catalog/programs/$programId/edit'
    | '/study-plans/$studyPlanId/details/edit'
    | '/study-plans/$studyPlanId/sections/new'
    | '/catalog/courses/$courseId'
    | '/catalog/programs/$programId'
    | '/study-plans/$studyPlanId/details'
    | '/study-plans/$studyPlanId/sections'
    | '/study-plans/$studyPlanId/sections/$sectionId/edit'
    | '/study-plans/$studyPlanId/sections/$sectionId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/_layout/catalog'
    | '/_layout/study-plans/$studyPlanId'
    | '/_layout/study-plans/new'
    | '/_layout/users/new'
    | '/_layout/catalog/'
    | '/_layout/study-plans/'
    | '/_layout/users/'
    | '/_layout/catalog/courses/new'
    | '/_layout/catalog/programs/new'
    | '/_layout/study-plans/$studyPlanId/courses'
    | '/_layout/study-plans/$studyPlanId/program-map'
    | '/_layout/catalog/courses/'
    | '/_layout/catalog/programs/'
    | '/_layout/catalog/courses/$courseId/edit'
    | '/_layout/catalog/programs/$programId/edit'
    | '/_layout/study-plans/$studyPlanId/details/edit'
    | '/_layout/study-plans/$studyPlanId/sections/new'
    | '/_layout/catalog/courses/$courseId/'
    | '/_layout/catalog/programs/$programId/'
    | '/_layout/study-plans/$studyPlanId/details/'
    | '/_layout/study-plans/$studyPlanId/sections/'
    | '/_layout/study-plans/$studyPlanId/sections/$sectionId/edit'
    | '/_layout/study-plans/$studyPlanId/sections/$sectionId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout/route.tsx",
      "children": [
        "/_layout/catalog",
        "/_layout/study-plans/$studyPlanId",
        "/_layout/study-plans/new",
        "/_layout/users/new",
        "/_layout/study-plans/",
        "/_layout/users/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_layout/catalog": {
      "filePath": "_layout/catalog/route.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/catalog/",
        "/_layout/catalog/courses/new",
        "/_layout/catalog/programs/new",
        "/_layout/catalog/courses/",
        "/_layout/catalog/programs/",
        "/_layout/catalog/courses/$courseId/edit",
        "/_layout/catalog/programs/$programId/edit",
        "/_layout/catalog/courses/$courseId/",
        "/_layout/catalog/programs/$programId/"
      ]
    },
    "/_layout/study-plans/$studyPlanId": {
      "filePath": "_layout/study-plans/$studyPlanId/route.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/study-plans/$studyPlanId/courses",
        "/_layout/study-plans/$studyPlanId/program-map",
        "/_layout/study-plans/$studyPlanId/details/edit",
        "/_layout/study-plans/$studyPlanId/sections/new",
        "/_layout/study-plans/$studyPlanId/details/",
        "/_layout/study-plans/$studyPlanId/sections/",
        "/_layout/study-plans/$studyPlanId/sections/$sectionId/edit",
        "/_layout/study-plans/$studyPlanId/sections/$sectionId/"
      ]
    },
    "/_layout/study-plans/new": {
      "filePath": "_layout/study-plans/new.tsx",
      "parent": "/_layout"
    },
    "/_layout/users/new": {
      "filePath": "_layout/users/new.tsx",
      "parent": "/_layout"
    },
    "/_layout/catalog/": {
      "filePath": "_layout/catalog/index.tsx",
      "parent": "/_layout/catalog"
    },
    "/_layout/study-plans/": {
      "filePath": "_layout/study-plans/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/users/": {
      "filePath": "_layout/users/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/catalog/courses/new": {
      "filePath": "_layout/catalog/courses/new.tsx",
      "parent": "/_layout/catalog"
    },
    "/_layout/catalog/programs/new": {
      "filePath": "_layout/catalog/programs/new.tsx",
      "parent": "/_layout/catalog"
    },
    "/_layout/study-plans/$studyPlanId/courses": {
      "filePath": "_layout/study-plans/$studyPlanId/courses.tsx",
      "parent": "/_layout/study-plans/$studyPlanId"
    },
    "/_layout/study-plans/$studyPlanId/program-map": {
      "filePath": "_layout/study-plans/$studyPlanId/program-map.tsx",
      "parent": "/_layout/study-plans/$studyPlanId"
    },
    "/_layout/catalog/courses/": {
      "filePath": "_layout/catalog/courses/index.tsx",
      "parent": "/_layout/catalog"
    },
    "/_layout/catalog/programs/": {
      "filePath": "_layout/catalog/programs/index.tsx",
      "parent": "/_layout/catalog"
    },
    "/_layout/catalog/courses/$courseId/edit": {
      "filePath": "_layout/catalog/courses/$courseId/edit.tsx",
      "parent": "/_layout/catalog"
    },
    "/_layout/catalog/programs/$programId/edit": {
      "filePath": "_layout/catalog/programs/$programId/edit.tsx",
      "parent": "/_layout/catalog"
    },
    "/_layout/study-plans/$studyPlanId/details/edit": {
      "filePath": "_layout/study-plans/$studyPlanId/details/edit.tsx",
      "parent": "/_layout/study-plans/$studyPlanId"
    },
    "/_layout/study-plans/$studyPlanId/sections/new": {
      "filePath": "_layout/study-plans/$studyPlanId/sections/new.tsx",
      "parent": "/_layout/study-plans/$studyPlanId"
    },
    "/_layout/catalog/courses/$courseId/": {
      "filePath": "_layout/catalog/courses/$courseId/index.tsx",
      "parent": "/_layout/catalog"
    },
    "/_layout/catalog/programs/$programId/": {
      "filePath": "_layout/catalog/programs/$programId/index.tsx",
      "parent": "/_layout/catalog"
    },
    "/_layout/study-plans/$studyPlanId/details/": {
      "filePath": "_layout/study-plans/$studyPlanId/details/index.tsx",
      "parent": "/_layout/study-plans/$studyPlanId"
    },
    "/_layout/study-plans/$studyPlanId/sections/": {
      "filePath": "_layout/study-plans/$studyPlanId/sections/index.tsx",
      "parent": "/_layout/study-plans/$studyPlanId"
    },
    "/_layout/study-plans/$studyPlanId/sections/$sectionId/edit": {
      "filePath": "_layout/study-plans/$studyPlanId/sections/$sectionId/edit.tsx",
      "parent": "/_layout/study-plans/$studyPlanId"
    },
    "/_layout/study-plans/$studyPlanId/sections/$sectionId/": {
      "filePath": "_layout/study-plans/$studyPlanId/sections/$sectionId/index.tsx",
      "parent": "/_layout/study-plans/$studyPlanId"
    }
  }
}
ROUTE_MANIFEST_END */
