/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout/route'
import { Route as OldStudyPlansStudyPlanLayoutImport } from './routes/old-study-plans/_studyPlanLayout'
import { Route as LayoutStudyPlansRouteImport } from './routes/_layout/study-plans/route'
import { Route as LayoutProgramsRouteImport } from './routes/_layout/programs/route'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard/route'
import { Route as LayoutCoursesRouteImport } from './routes/_layout/courses/route'
import { Route as LayoutActivityLogsRouteImport } from './routes/_layout/activity-logs/route'
import { Route as OldStudyPlansStudyPlanLayoutIndexImport } from './routes/old-study-plans/_studyPlanLayout/index'
import { Route as LayoutStudyPlansIndexImport } from './routes/_layout/study-plans/index'
import { Route as LayoutProgramsIndexImport } from './routes/_layout/programs/index'
import { Route as LayoutDashboardIndexImport } from './routes/_layout/dashboard/index'
import { Route as LayoutCoursesIndexImport } from './routes/_layout/courses/index'
import { Route as LayoutActivityLogsIndexImport } from './routes/_layout/activity-logs/index'
import { Route as OldStudyPlansStudyPlanLayoutProgramMapImport } from './routes/old-study-plans/_studyPlanLayout/program-map'
import { Route as OldStudyPlansStudyPlanLayoutFrameworkImport } from './routes/old-study-plans/_studyPlanLayout/framework'
import { Route as LayoutStudyPlansNewImport } from './routes/_layout/study-plans/new'
import { Route as LayoutProgramsNewImport } from './routes/_layout/programs/new'
import { Route as LayoutCoursesNewImport } from './routes/_layout/courses/new'
import { Route as LayoutStudyPlansStudyPlanIdRouteImport } from './routes/_layout/study-plans/$studyPlanId/route'
import { Route as LayoutProgramsProgramIdRouteImport } from './routes/_layout/programs/$programId/route'
import { Route as LayoutCoursesCourseIdRouteImport } from './routes/_layout/courses/$courseId/route'
import { Route as LayoutProgramsProgramIdIndexImport } from './routes/_layout/programs/$programId/index'
import { Route as LayoutCoursesCourseIdIndexImport } from './routes/_layout/courses/$courseId/index'
import { Route as LayoutStudyPlansStudyPlanIdProgramMapImport } from './routes/_layout/study-plans/$studyPlanId/program-map'
import { Route as LayoutStudyPlansStudyPlanIdOverviewImport } from './routes/_layout/study-plans/$studyPlanId/overview'
import { Route as LayoutStudyPlansStudyPlanIdFrameworkImport } from './routes/_layout/study-plans/$studyPlanId/framework'
import { Route as LayoutProgramsProgramIdEditImport } from './routes/_layout/programs/$programId/edit'
import { Route as LayoutCoursesCourseIdEditImport } from './routes/_layout/courses/$courseId/edit'
import { Route as LayoutStudyPlansStudyPlanIdDetailsRouteImport } from './routes/_layout/study-plans/$studyPlanId/details/route'
import { Route as LayoutStudyPlansStudyPlanIdDetailsIndexImport } from './routes/_layout/study-plans/$studyPlanId/details/index'
import { Route as LayoutStudyPlansStudyPlanIdDetailsEditImport } from './routes/_layout/study-plans/$studyPlanId/details/edit'

// Create Virtual Routes

const OldStudyPlansImport = createFileRoute('/old-study-plans')()

// Create/Update Routes

const OldStudyPlansRoute = OldStudyPlansImport.update({
  id: '/old-study-plans',
  path: '/old-study-plans',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRouteRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const OldStudyPlansStudyPlanLayoutRoute =
  OldStudyPlansStudyPlanLayoutImport.update({
    id: '/_studyPlanLayout',
    getParentRoute: () => OldStudyPlansRoute,
  } as any)

const LayoutStudyPlansRouteRoute = LayoutStudyPlansRouteImport.update({
  id: '/study-plans',
  path: '/study-plans',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutProgramsRouteRoute = LayoutProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutDashboardRouteRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutCoursesRouteRoute = LayoutCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const LayoutActivityLogsRouteRoute = LayoutActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => LayoutRouteRoute,
} as any)

const OldStudyPlansStudyPlanLayoutIndexRoute =
  OldStudyPlansStudyPlanLayoutIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OldStudyPlansStudyPlanLayoutRoute,
  } as any)

const LayoutStudyPlansIndexRoute = LayoutStudyPlansIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutStudyPlansRouteRoute,
} as any)

const LayoutProgramsIndexRoute = LayoutProgramsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutProgramsRouteRoute,
} as any)

const LayoutDashboardIndexRoute = LayoutDashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutDashboardRouteRoute,
} as any)

const LayoutCoursesIndexRoute = LayoutCoursesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutCoursesRouteRoute,
} as any)

const LayoutActivityLogsIndexRoute = LayoutActivityLogsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutActivityLogsRouteRoute,
} as any)

const OldStudyPlansStudyPlanLayoutProgramMapRoute =
  OldStudyPlansStudyPlanLayoutProgramMapImport.update({
    id: '/program-map',
    path: '/program-map',
    getParentRoute: () => OldStudyPlansStudyPlanLayoutRoute,
  } as any)

const OldStudyPlansStudyPlanLayoutFrameworkRoute =
  OldStudyPlansStudyPlanLayoutFrameworkImport.update({
    id: '/framework',
    path: '/framework',
    getParentRoute: () => OldStudyPlansStudyPlanLayoutRoute,
  } as any)

const LayoutStudyPlansNewRoute = LayoutStudyPlansNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutStudyPlansRouteRoute,
} as any)

const LayoutProgramsNewRoute = LayoutProgramsNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutProgramsRouteRoute,
} as any)

const LayoutCoursesNewRoute = LayoutCoursesNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutCoursesRouteRoute,
} as any)

const LayoutStudyPlansStudyPlanIdRouteRoute =
  LayoutStudyPlansStudyPlanIdRouteImport.update({
    id: '/$studyPlanId',
    path: '/$studyPlanId',
    getParentRoute: () => LayoutStudyPlansRouteRoute,
  } as any)

const LayoutProgramsProgramIdRouteRoute =
  LayoutProgramsProgramIdRouteImport.update({
    id: '/$programId',
    path: '/$programId',
    getParentRoute: () => LayoutProgramsRouteRoute,
  } as any)

const LayoutCoursesCourseIdRouteRoute = LayoutCoursesCourseIdRouteImport.update(
  {
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => LayoutCoursesRouteRoute,
  } as any,
)

const LayoutProgramsProgramIdIndexRoute =
  LayoutProgramsProgramIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutProgramsProgramIdRouteRoute,
  } as any)

const LayoutCoursesCourseIdIndexRoute = LayoutCoursesCourseIdIndexImport.update(
  {
    id: '/',
    path: '/',
    getParentRoute: () => LayoutCoursesCourseIdRouteRoute,
  } as any,
)

const LayoutStudyPlansStudyPlanIdProgramMapRoute =
  LayoutStudyPlansStudyPlanIdProgramMapImport.update({
    id: '/program-map',
    path: '/program-map',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

const LayoutStudyPlansStudyPlanIdOverviewRoute =
  LayoutStudyPlansStudyPlanIdOverviewImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

const LayoutStudyPlansStudyPlanIdFrameworkRoute =
  LayoutStudyPlansStudyPlanIdFrameworkImport.update({
    id: '/framework',
    path: '/framework',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

const LayoutProgramsProgramIdEditRoute =
  LayoutProgramsProgramIdEditImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => LayoutProgramsProgramIdRouteRoute,
  } as any)

const LayoutCoursesCourseIdEditRoute = LayoutCoursesCourseIdEditImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => LayoutCoursesCourseIdRouteRoute,
} as any)

const LayoutStudyPlansStudyPlanIdDetailsRouteRoute =
  LayoutStudyPlansStudyPlanIdDetailsRouteImport.update({
    id: '/details',
    path: '/details',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdRouteRoute,
  } as any)

const LayoutStudyPlansStudyPlanIdDetailsIndexRoute =
  LayoutStudyPlansStudyPlanIdDetailsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdDetailsRouteRoute,
  } as any)

const LayoutStudyPlansStudyPlanIdDetailsEditRoute =
  LayoutStudyPlansStudyPlanIdDetailsEditImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => LayoutStudyPlansStudyPlanIdDetailsRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/_layout/activity-logs': {
      id: '/_layout/activity-logs'
      path: '/activity-logs'
      fullPath: '/activity-logs'
      preLoaderRoute: typeof LayoutActivityLogsRouteImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/courses': {
      id: '/_layout/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof LayoutCoursesRouteImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/programs': {
      id: '/_layout/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof LayoutProgramsRouteImport
      parentRoute: typeof LayoutRouteImport
    }
    '/_layout/study-plans': {
      id: '/_layout/study-plans'
      path: '/study-plans'
      fullPath: '/study-plans'
      preLoaderRoute: typeof LayoutStudyPlansRouteImport
      parentRoute: typeof LayoutRouteImport
    }
    '/old-study-plans': {
      id: '/old-study-plans'
      path: '/old-study-plans'
      fullPath: '/old-study-plans'
      preLoaderRoute: typeof OldStudyPlansImport
      parentRoute: typeof rootRoute
    }
    '/old-study-plans/_studyPlanLayout': {
      id: '/old-study-plans/_studyPlanLayout'
      path: '/old-study-plans'
      fullPath: '/old-study-plans'
      preLoaderRoute: typeof OldStudyPlansStudyPlanLayoutImport
      parentRoute: typeof OldStudyPlansRoute
    }
    '/_layout/courses/$courseId': {
      id: '/_layout/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof LayoutCoursesCourseIdRouteImport
      parentRoute: typeof LayoutCoursesRouteImport
    }
    '/_layout/programs/$programId': {
      id: '/_layout/programs/$programId'
      path: '/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof LayoutProgramsProgramIdRouteImport
      parentRoute: typeof LayoutProgramsRouteImport
    }
    '/_layout/study-plans/$studyPlanId': {
      id: '/_layout/study-plans/$studyPlanId'
      path: '/$studyPlanId'
      fullPath: '/study-plans/$studyPlanId'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
      parentRoute: typeof LayoutStudyPlansRouteImport
    }
    '/_layout/courses/new': {
      id: '/_layout/courses/new'
      path: '/new'
      fullPath: '/courses/new'
      preLoaderRoute: typeof LayoutCoursesNewImport
      parentRoute: typeof LayoutCoursesRouteImport
    }
    '/_layout/programs/new': {
      id: '/_layout/programs/new'
      path: '/new'
      fullPath: '/programs/new'
      preLoaderRoute: typeof LayoutProgramsNewImport
      parentRoute: typeof LayoutProgramsRouteImport
    }
    '/_layout/study-plans/new': {
      id: '/_layout/study-plans/new'
      path: '/new'
      fullPath: '/study-plans/new'
      preLoaderRoute: typeof LayoutStudyPlansNewImport
      parentRoute: typeof LayoutStudyPlansRouteImport
    }
    '/old-study-plans/_studyPlanLayout/framework': {
      id: '/old-study-plans/_studyPlanLayout/framework'
      path: '/framework'
      fullPath: '/old-study-plans/framework'
      preLoaderRoute: typeof OldStudyPlansStudyPlanLayoutFrameworkImport
      parentRoute: typeof OldStudyPlansStudyPlanLayoutImport
    }
    '/old-study-plans/_studyPlanLayout/program-map': {
      id: '/old-study-plans/_studyPlanLayout/program-map'
      path: '/program-map'
      fullPath: '/old-study-plans/program-map'
      preLoaderRoute: typeof OldStudyPlansStudyPlanLayoutProgramMapImport
      parentRoute: typeof OldStudyPlansStudyPlanLayoutImport
    }
    '/_layout/activity-logs/': {
      id: '/_layout/activity-logs/'
      path: '/'
      fullPath: '/activity-logs/'
      preLoaderRoute: typeof LayoutActivityLogsIndexImport
      parentRoute: typeof LayoutActivityLogsRouteImport
    }
    '/_layout/courses/': {
      id: '/_layout/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof LayoutCoursesIndexImport
      parentRoute: typeof LayoutCoursesRouteImport
    }
    '/_layout/dashboard/': {
      id: '/_layout/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof LayoutDashboardIndexImport
      parentRoute: typeof LayoutDashboardRouteImport
    }
    '/_layout/programs/': {
      id: '/_layout/programs/'
      path: '/'
      fullPath: '/programs/'
      preLoaderRoute: typeof LayoutProgramsIndexImport
      parentRoute: typeof LayoutProgramsRouteImport
    }
    '/_layout/study-plans/': {
      id: '/_layout/study-plans/'
      path: '/'
      fullPath: '/study-plans/'
      preLoaderRoute: typeof LayoutStudyPlansIndexImport
      parentRoute: typeof LayoutStudyPlansRouteImport
    }
    '/old-study-plans/_studyPlanLayout/': {
      id: '/old-study-plans/_studyPlanLayout/'
      path: '/'
      fullPath: '/old-study-plans/'
      preLoaderRoute: typeof OldStudyPlansStudyPlanLayoutIndexImport
      parentRoute: typeof OldStudyPlansStudyPlanLayoutImport
    }
    '/_layout/study-plans/$studyPlanId/details': {
      id: '/_layout/study-plans/$studyPlanId/details'
      path: '/details'
      fullPath: '/study-plans/$studyPlanId/details'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdDetailsRouteImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
    '/_layout/courses/$courseId/edit': {
      id: '/_layout/courses/$courseId/edit'
      path: '/edit'
      fullPath: '/courses/$courseId/edit'
      preLoaderRoute: typeof LayoutCoursesCourseIdEditImport
      parentRoute: typeof LayoutCoursesCourseIdRouteImport
    }
    '/_layout/programs/$programId/edit': {
      id: '/_layout/programs/$programId/edit'
      path: '/edit'
      fullPath: '/programs/$programId/edit'
      preLoaderRoute: typeof LayoutProgramsProgramIdEditImport
      parentRoute: typeof LayoutProgramsProgramIdRouteImport
    }
    '/_layout/study-plans/$studyPlanId/framework': {
      id: '/_layout/study-plans/$studyPlanId/framework'
      path: '/framework'
      fullPath: '/study-plans/$studyPlanId/framework'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdFrameworkImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
    '/_layout/study-plans/$studyPlanId/overview': {
      id: '/_layout/study-plans/$studyPlanId/overview'
      path: '/overview'
      fullPath: '/study-plans/$studyPlanId/overview'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdOverviewImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
    '/_layout/study-plans/$studyPlanId/program-map': {
      id: '/_layout/study-plans/$studyPlanId/program-map'
      path: '/program-map'
      fullPath: '/study-plans/$studyPlanId/program-map'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdProgramMapImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdRouteImport
    }
    '/_layout/courses/$courseId/': {
      id: '/_layout/courses/$courseId/'
      path: '/'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof LayoutCoursesCourseIdIndexImport
      parentRoute: typeof LayoutCoursesCourseIdRouteImport
    }
    '/_layout/programs/$programId/': {
      id: '/_layout/programs/$programId/'
      path: '/'
      fullPath: '/programs/$programId/'
      preLoaderRoute: typeof LayoutProgramsProgramIdIndexImport
      parentRoute: typeof LayoutProgramsProgramIdRouteImport
    }
    '/_layout/study-plans/$studyPlanId/details/edit': {
      id: '/_layout/study-plans/$studyPlanId/details/edit'
      path: '/edit'
      fullPath: '/study-plans/$studyPlanId/details/edit'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdDetailsEditImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdDetailsRouteImport
    }
    '/_layout/study-plans/$studyPlanId/details/': {
      id: '/_layout/study-plans/$studyPlanId/details/'
      path: '/'
      fullPath: '/study-plans/$studyPlanId/details/'
      preLoaderRoute: typeof LayoutStudyPlansStudyPlanIdDetailsIndexImport
      parentRoute: typeof LayoutStudyPlansStudyPlanIdDetailsRouteImport
    }
  }
}

// Create and export the route tree

interface LayoutActivityLogsRouteRouteChildren {
  LayoutActivityLogsIndexRoute: typeof LayoutActivityLogsIndexRoute
}

const LayoutActivityLogsRouteRouteChildren: LayoutActivityLogsRouteRouteChildren =
  {
    LayoutActivityLogsIndexRoute: LayoutActivityLogsIndexRoute,
  }

const LayoutActivityLogsRouteRouteWithChildren =
  LayoutActivityLogsRouteRoute._addFileChildren(
    LayoutActivityLogsRouteRouteChildren,
  )

interface LayoutCoursesCourseIdRouteRouteChildren {
  LayoutCoursesCourseIdEditRoute: typeof LayoutCoursesCourseIdEditRoute
  LayoutCoursesCourseIdIndexRoute: typeof LayoutCoursesCourseIdIndexRoute
}

const LayoutCoursesCourseIdRouteRouteChildren: LayoutCoursesCourseIdRouteRouteChildren =
  {
    LayoutCoursesCourseIdEditRoute: LayoutCoursesCourseIdEditRoute,
    LayoutCoursesCourseIdIndexRoute: LayoutCoursesCourseIdIndexRoute,
  }

const LayoutCoursesCourseIdRouteRouteWithChildren =
  LayoutCoursesCourseIdRouteRoute._addFileChildren(
    LayoutCoursesCourseIdRouteRouteChildren,
  )

interface LayoutCoursesRouteRouteChildren {
  LayoutCoursesCourseIdRouteRoute: typeof LayoutCoursesCourseIdRouteRouteWithChildren
  LayoutCoursesNewRoute: typeof LayoutCoursesNewRoute
  LayoutCoursesIndexRoute: typeof LayoutCoursesIndexRoute
}

const LayoutCoursesRouteRouteChildren: LayoutCoursesRouteRouteChildren = {
  LayoutCoursesCourseIdRouteRoute: LayoutCoursesCourseIdRouteRouteWithChildren,
  LayoutCoursesNewRoute: LayoutCoursesNewRoute,
  LayoutCoursesIndexRoute: LayoutCoursesIndexRoute,
}

const LayoutCoursesRouteRouteWithChildren =
  LayoutCoursesRouteRoute._addFileChildren(LayoutCoursesRouteRouteChildren)

interface LayoutDashboardRouteRouteChildren {
  LayoutDashboardIndexRoute: typeof LayoutDashboardIndexRoute
}

const LayoutDashboardRouteRouteChildren: LayoutDashboardRouteRouteChildren = {
  LayoutDashboardIndexRoute: LayoutDashboardIndexRoute,
}

const LayoutDashboardRouteRouteWithChildren =
  LayoutDashboardRouteRoute._addFileChildren(LayoutDashboardRouteRouteChildren)

interface LayoutProgramsProgramIdRouteRouteChildren {
  LayoutProgramsProgramIdEditRoute: typeof LayoutProgramsProgramIdEditRoute
  LayoutProgramsProgramIdIndexRoute: typeof LayoutProgramsProgramIdIndexRoute
}

const LayoutProgramsProgramIdRouteRouteChildren: LayoutProgramsProgramIdRouteRouteChildren =
  {
    LayoutProgramsProgramIdEditRoute: LayoutProgramsProgramIdEditRoute,
    LayoutProgramsProgramIdIndexRoute: LayoutProgramsProgramIdIndexRoute,
  }

const LayoutProgramsProgramIdRouteRouteWithChildren =
  LayoutProgramsProgramIdRouteRoute._addFileChildren(
    LayoutProgramsProgramIdRouteRouteChildren,
  )

interface LayoutProgramsRouteRouteChildren {
  LayoutProgramsProgramIdRouteRoute: typeof LayoutProgramsProgramIdRouteRouteWithChildren
  LayoutProgramsNewRoute: typeof LayoutProgramsNewRoute
  LayoutProgramsIndexRoute: typeof LayoutProgramsIndexRoute
}

const LayoutProgramsRouteRouteChildren: LayoutProgramsRouteRouteChildren = {
  LayoutProgramsProgramIdRouteRoute:
    LayoutProgramsProgramIdRouteRouteWithChildren,
  LayoutProgramsNewRoute: LayoutProgramsNewRoute,
  LayoutProgramsIndexRoute: LayoutProgramsIndexRoute,
}

const LayoutProgramsRouteRouteWithChildren =
  LayoutProgramsRouteRoute._addFileChildren(LayoutProgramsRouteRouteChildren)

interface LayoutStudyPlansStudyPlanIdDetailsRouteRouteChildren {
  LayoutStudyPlansStudyPlanIdDetailsEditRoute: typeof LayoutStudyPlansStudyPlanIdDetailsEditRoute
  LayoutStudyPlansStudyPlanIdDetailsIndexRoute: typeof LayoutStudyPlansStudyPlanIdDetailsIndexRoute
}

const LayoutStudyPlansStudyPlanIdDetailsRouteRouteChildren: LayoutStudyPlansStudyPlanIdDetailsRouteRouteChildren =
  {
    LayoutStudyPlansStudyPlanIdDetailsEditRoute:
      LayoutStudyPlansStudyPlanIdDetailsEditRoute,
    LayoutStudyPlansStudyPlanIdDetailsIndexRoute:
      LayoutStudyPlansStudyPlanIdDetailsIndexRoute,
  }

const LayoutStudyPlansStudyPlanIdDetailsRouteRouteWithChildren =
  LayoutStudyPlansStudyPlanIdDetailsRouteRoute._addFileChildren(
    LayoutStudyPlansStudyPlanIdDetailsRouteRouteChildren,
  )

interface LayoutStudyPlansStudyPlanIdRouteRouteChildren {
  LayoutStudyPlansStudyPlanIdDetailsRouteRoute: typeof LayoutStudyPlansStudyPlanIdDetailsRouteRouteWithChildren
  LayoutStudyPlansStudyPlanIdFrameworkRoute: typeof LayoutStudyPlansStudyPlanIdFrameworkRoute
  LayoutStudyPlansStudyPlanIdOverviewRoute: typeof LayoutStudyPlansStudyPlanIdOverviewRoute
  LayoutStudyPlansStudyPlanIdProgramMapRoute: typeof LayoutStudyPlansStudyPlanIdProgramMapRoute
}

const LayoutStudyPlansStudyPlanIdRouteRouteChildren: LayoutStudyPlansStudyPlanIdRouteRouteChildren =
  {
    LayoutStudyPlansStudyPlanIdDetailsRouteRoute:
      LayoutStudyPlansStudyPlanIdDetailsRouteRouteWithChildren,
    LayoutStudyPlansStudyPlanIdFrameworkRoute:
      LayoutStudyPlansStudyPlanIdFrameworkRoute,
    LayoutStudyPlansStudyPlanIdOverviewRoute:
      LayoutStudyPlansStudyPlanIdOverviewRoute,
    LayoutStudyPlansStudyPlanIdProgramMapRoute:
      LayoutStudyPlansStudyPlanIdProgramMapRoute,
  }

const LayoutStudyPlansStudyPlanIdRouteRouteWithChildren =
  LayoutStudyPlansStudyPlanIdRouteRoute._addFileChildren(
    LayoutStudyPlansStudyPlanIdRouteRouteChildren,
  )

interface LayoutStudyPlansRouteRouteChildren {
  LayoutStudyPlansStudyPlanIdRouteRoute: typeof LayoutStudyPlansStudyPlanIdRouteRouteWithChildren
  LayoutStudyPlansNewRoute: typeof LayoutStudyPlansNewRoute
  LayoutStudyPlansIndexRoute: typeof LayoutStudyPlansIndexRoute
}

const LayoutStudyPlansRouteRouteChildren: LayoutStudyPlansRouteRouteChildren = {
  LayoutStudyPlansStudyPlanIdRouteRoute:
    LayoutStudyPlansStudyPlanIdRouteRouteWithChildren,
  LayoutStudyPlansNewRoute: LayoutStudyPlansNewRoute,
  LayoutStudyPlansIndexRoute: LayoutStudyPlansIndexRoute,
}

const LayoutStudyPlansRouteRouteWithChildren =
  LayoutStudyPlansRouteRoute._addFileChildren(
    LayoutStudyPlansRouteRouteChildren,
  )

interface LayoutRouteRouteChildren {
  LayoutActivityLogsRouteRoute: typeof LayoutActivityLogsRouteRouteWithChildren
  LayoutCoursesRouteRoute: typeof LayoutCoursesRouteRouteWithChildren
  LayoutDashboardRouteRoute: typeof LayoutDashboardRouteRouteWithChildren
  LayoutProgramsRouteRoute: typeof LayoutProgramsRouteRouteWithChildren
  LayoutStudyPlansRouteRoute: typeof LayoutStudyPlansRouteRouteWithChildren
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutActivityLogsRouteRoute: LayoutActivityLogsRouteRouteWithChildren,
  LayoutCoursesRouteRoute: LayoutCoursesRouteRouteWithChildren,
  LayoutDashboardRouteRoute: LayoutDashboardRouteRouteWithChildren,
  LayoutProgramsRouteRoute: LayoutProgramsRouteRouteWithChildren,
  LayoutStudyPlansRouteRoute: LayoutStudyPlansRouteRouteWithChildren,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

interface OldStudyPlansStudyPlanLayoutRouteChildren {
  OldStudyPlansStudyPlanLayoutFrameworkRoute: typeof OldStudyPlansStudyPlanLayoutFrameworkRoute
  OldStudyPlansStudyPlanLayoutProgramMapRoute: typeof OldStudyPlansStudyPlanLayoutProgramMapRoute
  OldStudyPlansStudyPlanLayoutIndexRoute: typeof OldStudyPlansStudyPlanLayoutIndexRoute
}

const OldStudyPlansStudyPlanLayoutRouteChildren: OldStudyPlansStudyPlanLayoutRouteChildren =
  {
    OldStudyPlansStudyPlanLayoutFrameworkRoute:
      OldStudyPlansStudyPlanLayoutFrameworkRoute,
    OldStudyPlansStudyPlanLayoutProgramMapRoute:
      OldStudyPlansStudyPlanLayoutProgramMapRoute,
    OldStudyPlansStudyPlanLayoutIndexRoute:
      OldStudyPlansStudyPlanLayoutIndexRoute,
  }

const OldStudyPlansStudyPlanLayoutRouteWithChildren =
  OldStudyPlansStudyPlanLayoutRoute._addFileChildren(
    OldStudyPlansStudyPlanLayoutRouteChildren,
  )

interface OldStudyPlansRouteChildren {
  OldStudyPlansStudyPlanLayoutRoute: typeof OldStudyPlansStudyPlanLayoutRouteWithChildren
}

const OldStudyPlansRouteChildren: OldStudyPlansRouteChildren = {
  OldStudyPlansStudyPlanLayoutRoute:
    OldStudyPlansStudyPlanLayoutRouteWithChildren,
}

const OldStudyPlansRouteWithChildren = OldStudyPlansRoute._addFileChildren(
  OldStudyPlansRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteRouteWithChildren
  '/activity-logs': typeof LayoutActivityLogsRouteRouteWithChildren
  '/courses': typeof LayoutCoursesRouteRouteWithChildren
  '/dashboard': typeof LayoutDashboardRouteRouteWithChildren
  '/programs': typeof LayoutProgramsRouteRouteWithChildren
  '/study-plans': typeof LayoutStudyPlansRouteRouteWithChildren
  '/old-study-plans': typeof OldStudyPlansStudyPlanLayoutRouteWithChildren
  '/courses/$courseId': typeof LayoutCoursesCourseIdRouteRouteWithChildren
  '/programs/$programId': typeof LayoutProgramsProgramIdRouteRouteWithChildren
  '/study-plans/$studyPlanId': typeof LayoutStudyPlansStudyPlanIdRouteRouteWithChildren
  '/courses/new': typeof LayoutCoursesNewRoute
  '/programs/new': typeof LayoutProgramsNewRoute
  '/study-plans/new': typeof LayoutStudyPlansNewRoute
  '/old-study-plans/framework': typeof OldStudyPlansStudyPlanLayoutFrameworkRoute
  '/old-study-plans/program-map': typeof OldStudyPlansStudyPlanLayoutProgramMapRoute
  '/activity-logs/': typeof LayoutActivityLogsIndexRoute
  '/courses/': typeof LayoutCoursesIndexRoute
  '/dashboard/': typeof LayoutDashboardIndexRoute
  '/programs/': typeof LayoutProgramsIndexRoute
  '/study-plans/': typeof LayoutStudyPlansIndexRoute
  '/old-study-plans/': typeof OldStudyPlansStudyPlanLayoutIndexRoute
  '/study-plans/$studyPlanId/details': typeof LayoutStudyPlansStudyPlanIdDetailsRouteRouteWithChildren
  '/courses/$courseId/edit': typeof LayoutCoursesCourseIdEditRoute
  '/programs/$programId/edit': typeof LayoutProgramsProgramIdEditRoute
  '/study-plans/$studyPlanId/framework': typeof LayoutStudyPlansStudyPlanIdFrameworkRoute
  '/study-plans/$studyPlanId/overview': typeof LayoutStudyPlansStudyPlanIdOverviewRoute
  '/study-plans/$studyPlanId/program-map': typeof LayoutStudyPlansStudyPlanIdProgramMapRoute
  '/courses/$courseId/': typeof LayoutCoursesCourseIdIndexRoute
  '/programs/$programId/': typeof LayoutProgramsProgramIdIndexRoute
  '/study-plans/$studyPlanId/details/edit': typeof LayoutStudyPlansStudyPlanIdDetailsEditRoute
  '/study-plans/$studyPlanId/details/': typeof LayoutStudyPlansStudyPlanIdDetailsIndexRoute
}

export interface FileRoutesByTo {
  '': typeof LayoutRouteRouteWithChildren
  '/old-study-plans': typeof OldStudyPlansStudyPlanLayoutIndexRoute
  '/study-plans/$studyPlanId': typeof LayoutStudyPlansStudyPlanIdRouteRouteWithChildren
  '/courses/new': typeof LayoutCoursesNewRoute
  '/programs/new': typeof LayoutProgramsNewRoute
  '/study-plans/new': typeof LayoutStudyPlansNewRoute
  '/old-study-plans/framework': typeof OldStudyPlansStudyPlanLayoutFrameworkRoute
  '/old-study-plans/program-map': typeof OldStudyPlansStudyPlanLayoutProgramMapRoute
  '/activity-logs': typeof LayoutActivityLogsIndexRoute
  '/courses': typeof LayoutCoursesIndexRoute
  '/dashboard': typeof LayoutDashboardIndexRoute
  '/programs': typeof LayoutProgramsIndexRoute
  '/study-plans': typeof LayoutStudyPlansIndexRoute
  '/courses/$courseId/edit': typeof LayoutCoursesCourseIdEditRoute
  '/programs/$programId/edit': typeof LayoutProgramsProgramIdEditRoute
  '/study-plans/$studyPlanId/framework': typeof LayoutStudyPlansStudyPlanIdFrameworkRoute
  '/study-plans/$studyPlanId/overview': typeof LayoutStudyPlansStudyPlanIdOverviewRoute
  '/study-plans/$studyPlanId/program-map': typeof LayoutStudyPlansStudyPlanIdProgramMapRoute
  '/courses/$courseId': typeof LayoutCoursesCourseIdIndexRoute
  '/programs/$programId': typeof LayoutProgramsProgramIdIndexRoute
  '/study-plans/$studyPlanId/details/edit': typeof LayoutStudyPlansStudyPlanIdDetailsEditRoute
  '/study-plans/$studyPlanId/details': typeof LayoutStudyPlansStudyPlanIdDetailsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/_layout/activity-logs': typeof LayoutActivityLogsRouteRouteWithChildren
  '/_layout/courses': typeof LayoutCoursesRouteRouteWithChildren
  '/_layout/dashboard': typeof LayoutDashboardRouteRouteWithChildren
  '/_layout/programs': typeof LayoutProgramsRouteRouteWithChildren
  '/_layout/study-plans': typeof LayoutStudyPlansRouteRouteWithChildren
  '/old-study-plans': typeof OldStudyPlansRouteWithChildren
  '/old-study-plans/_studyPlanLayout': typeof OldStudyPlansStudyPlanLayoutRouteWithChildren
  '/_layout/courses/$courseId': typeof LayoutCoursesCourseIdRouteRouteWithChildren
  '/_layout/programs/$programId': typeof LayoutProgramsProgramIdRouteRouteWithChildren
  '/_layout/study-plans/$studyPlanId': typeof LayoutStudyPlansStudyPlanIdRouteRouteWithChildren
  '/_layout/courses/new': typeof LayoutCoursesNewRoute
  '/_layout/programs/new': typeof LayoutProgramsNewRoute
  '/_layout/study-plans/new': typeof LayoutStudyPlansNewRoute
  '/old-study-plans/_studyPlanLayout/framework': typeof OldStudyPlansStudyPlanLayoutFrameworkRoute
  '/old-study-plans/_studyPlanLayout/program-map': typeof OldStudyPlansStudyPlanLayoutProgramMapRoute
  '/_layout/activity-logs/': typeof LayoutActivityLogsIndexRoute
  '/_layout/courses/': typeof LayoutCoursesIndexRoute
  '/_layout/dashboard/': typeof LayoutDashboardIndexRoute
  '/_layout/programs/': typeof LayoutProgramsIndexRoute
  '/_layout/study-plans/': typeof LayoutStudyPlansIndexRoute
  '/old-study-plans/_studyPlanLayout/': typeof OldStudyPlansStudyPlanLayoutIndexRoute
  '/_layout/study-plans/$studyPlanId/details': typeof LayoutStudyPlansStudyPlanIdDetailsRouteRouteWithChildren
  '/_layout/courses/$courseId/edit': typeof LayoutCoursesCourseIdEditRoute
  '/_layout/programs/$programId/edit': typeof LayoutProgramsProgramIdEditRoute
  '/_layout/study-plans/$studyPlanId/framework': typeof LayoutStudyPlansStudyPlanIdFrameworkRoute
  '/_layout/study-plans/$studyPlanId/overview': typeof LayoutStudyPlansStudyPlanIdOverviewRoute
  '/_layout/study-plans/$studyPlanId/program-map': typeof LayoutStudyPlansStudyPlanIdProgramMapRoute
  '/_layout/courses/$courseId/': typeof LayoutCoursesCourseIdIndexRoute
  '/_layout/programs/$programId/': typeof LayoutProgramsProgramIdIndexRoute
  '/_layout/study-plans/$studyPlanId/details/edit': typeof LayoutStudyPlansStudyPlanIdDetailsEditRoute
  '/_layout/study-plans/$studyPlanId/details/': typeof LayoutStudyPlansStudyPlanIdDetailsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/activity-logs'
    | '/courses'
    | '/dashboard'
    | '/programs'
    | '/study-plans'
    | '/old-study-plans'
    | '/courses/$courseId'
    | '/programs/$programId'
    | '/study-plans/$studyPlanId'
    | '/courses/new'
    | '/programs/new'
    | '/study-plans/new'
    | '/old-study-plans/framework'
    | '/old-study-plans/program-map'
    | '/activity-logs/'
    | '/courses/'
    | '/dashboard/'
    | '/programs/'
    | '/study-plans/'
    | '/old-study-plans/'
    | '/study-plans/$studyPlanId/details'
    | '/courses/$courseId/edit'
    | '/programs/$programId/edit'
    | '/study-plans/$studyPlanId/framework'
    | '/study-plans/$studyPlanId/overview'
    | '/study-plans/$studyPlanId/program-map'
    | '/courses/$courseId/'
    | '/programs/$programId/'
    | '/study-plans/$studyPlanId/details/edit'
    | '/study-plans/$studyPlanId/details/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/old-study-plans'
    | '/study-plans/$studyPlanId'
    | '/courses/new'
    | '/programs/new'
    | '/study-plans/new'
    | '/old-study-plans/framework'
    | '/old-study-plans/program-map'
    | '/activity-logs'
    | '/courses'
    | '/dashboard'
    | '/programs'
    | '/study-plans'
    | '/courses/$courseId/edit'
    | '/programs/$programId/edit'
    | '/study-plans/$studyPlanId/framework'
    | '/study-plans/$studyPlanId/overview'
    | '/study-plans/$studyPlanId/program-map'
    | '/courses/$courseId'
    | '/programs/$programId'
    | '/study-plans/$studyPlanId/details/edit'
    | '/study-plans/$studyPlanId/details'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/activity-logs'
    | '/_layout/courses'
    | '/_layout/dashboard'
    | '/_layout/programs'
    | '/_layout/study-plans'
    | '/old-study-plans'
    | '/old-study-plans/_studyPlanLayout'
    | '/_layout/courses/$courseId'
    | '/_layout/programs/$programId'
    | '/_layout/study-plans/$studyPlanId'
    | '/_layout/courses/new'
    | '/_layout/programs/new'
    | '/_layout/study-plans/new'
    | '/old-study-plans/_studyPlanLayout/framework'
    | '/old-study-plans/_studyPlanLayout/program-map'
    | '/_layout/activity-logs/'
    | '/_layout/courses/'
    | '/_layout/dashboard/'
    | '/_layout/programs/'
    | '/_layout/study-plans/'
    | '/old-study-plans/_studyPlanLayout/'
    | '/_layout/study-plans/$studyPlanId/details'
    | '/_layout/courses/$courseId/edit'
    | '/_layout/programs/$programId/edit'
    | '/_layout/study-plans/$studyPlanId/framework'
    | '/_layout/study-plans/$studyPlanId/overview'
    | '/_layout/study-plans/$studyPlanId/program-map'
    | '/_layout/courses/$courseId/'
    | '/_layout/programs/$programId/'
    | '/_layout/study-plans/$studyPlanId/details/edit'
    | '/_layout/study-plans/$studyPlanId/details/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  OldStudyPlansRoute: typeof OldStudyPlansRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  OldStudyPlansRoute: OldStudyPlansRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/old-study-plans"
      ]
    },
    "/_layout": {
      "filePath": "_layout/route.tsx",
      "children": [
        "/_layout/activity-logs",
        "/_layout/courses",
        "/_layout/dashboard",
        "/_layout/programs",
        "/_layout/study-plans"
      ]
    },
    "/_layout/activity-logs": {
      "filePath": "_layout/activity-logs/route.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/activity-logs/"
      ]
    },
    "/_layout/courses": {
      "filePath": "_layout/courses/route.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/courses/$courseId",
        "/_layout/courses/new",
        "/_layout/courses/"
      ]
    },
    "/_layout/dashboard": {
      "filePath": "_layout/dashboard/route.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/dashboard/"
      ]
    },
    "/_layout/programs": {
      "filePath": "_layout/programs/route.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/programs/$programId",
        "/_layout/programs/new",
        "/_layout/programs/"
      ]
    },
    "/_layout/study-plans": {
      "filePath": "_layout/study-plans/route.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/study-plans/$studyPlanId",
        "/_layout/study-plans/new",
        "/_layout/study-plans/"
      ]
    },
    "/old-study-plans": {
      "filePath": "old-study-plans",
      "children": [
        "/old-study-plans/_studyPlanLayout"
      ]
    },
    "/old-study-plans/_studyPlanLayout": {
      "filePath": "old-study-plans/_studyPlanLayout.tsx",
      "parent": "/old-study-plans",
      "children": [
        "/old-study-plans/_studyPlanLayout/framework",
        "/old-study-plans/_studyPlanLayout/program-map",
        "/old-study-plans/_studyPlanLayout/"
      ]
    },
    "/_layout/courses/$courseId": {
      "filePath": "_layout/courses/$courseId/route.tsx",
      "parent": "/_layout/courses",
      "children": [
        "/_layout/courses/$courseId/edit",
        "/_layout/courses/$courseId/"
      ]
    },
    "/_layout/programs/$programId": {
      "filePath": "_layout/programs/$programId/route.tsx",
      "parent": "/_layout/programs",
      "children": [
        "/_layout/programs/$programId/edit",
        "/_layout/programs/$programId/"
      ]
    },
    "/_layout/study-plans/$studyPlanId": {
      "filePath": "_layout/study-plans/$studyPlanId/route.tsx",
      "parent": "/_layout/study-plans",
      "children": [
        "/_layout/study-plans/$studyPlanId/details",
        "/_layout/study-plans/$studyPlanId/framework",
        "/_layout/study-plans/$studyPlanId/overview",
        "/_layout/study-plans/$studyPlanId/program-map"
      ]
    },
    "/_layout/courses/new": {
      "filePath": "_layout/courses/new.tsx",
      "parent": "/_layout/courses"
    },
    "/_layout/programs/new": {
      "filePath": "_layout/programs/new.tsx",
      "parent": "/_layout/programs"
    },
    "/_layout/study-plans/new": {
      "filePath": "_layout/study-plans/new.tsx",
      "parent": "/_layout/study-plans"
    },
    "/old-study-plans/_studyPlanLayout/framework": {
      "filePath": "old-study-plans/_studyPlanLayout/framework.tsx",
      "parent": "/old-study-plans/_studyPlanLayout"
    },
    "/old-study-plans/_studyPlanLayout/program-map": {
      "filePath": "old-study-plans/_studyPlanLayout/program-map.tsx",
      "parent": "/old-study-plans/_studyPlanLayout"
    },
    "/_layout/activity-logs/": {
      "filePath": "_layout/activity-logs/index.tsx",
      "parent": "/_layout/activity-logs"
    },
    "/_layout/courses/": {
      "filePath": "_layout/courses/index.tsx",
      "parent": "/_layout/courses"
    },
    "/_layout/dashboard/": {
      "filePath": "_layout/dashboard/index.tsx",
      "parent": "/_layout/dashboard"
    },
    "/_layout/programs/": {
      "filePath": "_layout/programs/index.tsx",
      "parent": "/_layout/programs"
    },
    "/_layout/study-plans/": {
      "filePath": "_layout/study-plans/index.tsx",
      "parent": "/_layout/study-plans"
    },
    "/old-study-plans/_studyPlanLayout/": {
      "filePath": "old-study-plans/_studyPlanLayout/index.tsx",
      "parent": "/old-study-plans/_studyPlanLayout"
    },
    "/_layout/study-plans/$studyPlanId/details": {
      "filePath": "_layout/study-plans/$studyPlanId/details/route.tsx",
      "parent": "/_layout/study-plans/$studyPlanId",
      "children": [
        "/_layout/study-plans/$studyPlanId/details/edit",
        "/_layout/study-plans/$studyPlanId/details/"
      ]
    },
    "/_layout/courses/$courseId/edit": {
      "filePath": "_layout/courses/$courseId/edit.tsx",
      "parent": "/_layout/courses/$courseId"
    },
    "/_layout/programs/$programId/edit": {
      "filePath": "_layout/programs/$programId/edit.tsx",
      "parent": "/_layout/programs/$programId"
    },
    "/_layout/study-plans/$studyPlanId/framework": {
      "filePath": "_layout/study-plans/$studyPlanId/framework.tsx",
      "parent": "/_layout/study-plans/$studyPlanId"
    },
    "/_layout/study-plans/$studyPlanId/overview": {
      "filePath": "_layout/study-plans/$studyPlanId/overview.tsx",
      "parent": "/_layout/study-plans/$studyPlanId"
    },
    "/_layout/study-plans/$studyPlanId/program-map": {
      "filePath": "_layout/study-plans/$studyPlanId/program-map.tsx",
      "parent": "/_layout/study-plans/$studyPlanId"
    },
    "/_layout/courses/$courseId/": {
      "filePath": "_layout/courses/$courseId/index.tsx",
      "parent": "/_layout/courses/$courseId"
    },
    "/_layout/programs/$programId/": {
      "filePath": "_layout/programs/$programId/index.tsx",
      "parent": "/_layout/programs/$programId"
    },
    "/_layout/study-plans/$studyPlanId/details/edit": {
      "filePath": "_layout/study-plans/$studyPlanId/details/edit.tsx",
      "parent": "/_layout/study-plans/$studyPlanId/details"
    },
    "/_layout/study-plans/$studyPlanId/details/": {
      "filePath": "_layout/study-plans/$studyPlanId/details/index.tsx",
      "parent": "/_layout/study-plans/$studyPlanId/details"
    }
  }
}
ROUTE_MANIFEST_END */
