/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as StudyPlansStudyPlanIdImport } from './routes/study-plans.$studyPlanId'
import { Route as StudyPlansStudyPlanIdProgramMapImport } from './routes/study-plans.$studyPlanId.program-map'
import { Route as StudyPlansStudyPlanIdOverviewImport } from './routes/study-plans.$studyPlanId.overview'
import { Route as StudyPlansStudyPlanIdFrameworkImport } from './routes/study-plans.$studyPlanId.framework'
import { Route as ProgramsProgramIdStudyPlansImport } from './routes/programs.$programId.study-plans'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StudyPlansStudyPlanIdRoute = StudyPlansStudyPlanIdImport.update({
  id: '/study-plans/$studyPlanId',
  path: '/study-plans/$studyPlanId',
  getParentRoute: () => rootRoute,
} as any)

const StudyPlansStudyPlanIdProgramMapRoute =
  StudyPlansStudyPlanIdProgramMapImport.update({
    id: '/program-map',
    path: '/program-map',
    getParentRoute: () => StudyPlansStudyPlanIdRoute,
  } as any)

const StudyPlansStudyPlanIdOverviewRoute =
  StudyPlansStudyPlanIdOverviewImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => StudyPlansStudyPlanIdRoute,
  } as any)

const StudyPlansStudyPlanIdFrameworkRoute =
  StudyPlansStudyPlanIdFrameworkImport.update({
    id: '/framework',
    path: '/framework',
    getParentRoute: () => StudyPlansStudyPlanIdRoute,
  } as any)

const ProgramsProgramIdStudyPlansRoute =
  ProgramsProgramIdStudyPlansImport.update({
    id: '/programs/$programId/study-plans',
    path: '/programs/$programId/study-plans',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/study-plans/$studyPlanId': {
      id: '/study-plans/$studyPlanId'
      path: '/study-plans/$studyPlanId'
      fullPath: '/study-plans/$studyPlanId'
      preLoaderRoute: typeof StudyPlansStudyPlanIdImport
      parentRoute: typeof rootRoute
    }
    '/programs/$programId/study-plans': {
      id: '/programs/$programId/study-plans'
      path: '/programs/$programId/study-plans'
      fullPath: '/programs/$programId/study-plans'
      preLoaderRoute: typeof ProgramsProgramIdStudyPlansImport
      parentRoute: typeof rootRoute
    }
    '/study-plans/$studyPlanId/framework': {
      id: '/study-plans/$studyPlanId/framework'
      path: '/framework'
      fullPath: '/study-plans/$studyPlanId/framework'
      preLoaderRoute: typeof StudyPlansStudyPlanIdFrameworkImport
      parentRoute: typeof StudyPlansStudyPlanIdImport
    }
    '/study-plans/$studyPlanId/overview': {
      id: '/study-plans/$studyPlanId/overview'
      path: '/overview'
      fullPath: '/study-plans/$studyPlanId/overview'
      preLoaderRoute: typeof StudyPlansStudyPlanIdOverviewImport
      parentRoute: typeof StudyPlansStudyPlanIdImport
    }
    '/study-plans/$studyPlanId/program-map': {
      id: '/study-plans/$studyPlanId/program-map'
      path: '/program-map'
      fullPath: '/study-plans/$studyPlanId/program-map'
      preLoaderRoute: typeof StudyPlansStudyPlanIdProgramMapImport
      parentRoute: typeof StudyPlansStudyPlanIdImport
    }
  }
}

// Create and export the route tree

interface StudyPlansStudyPlanIdRouteChildren {
  StudyPlansStudyPlanIdFrameworkRoute: typeof StudyPlansStudyPlanIdFrameworkRoute
  StudyPlansStudyPlanIdOverviewRoute: typeof StudyPlansStudyPlanIdOverviewRoute
  StudyPlansStudyPlanIdProgramMapRoute: typeof StudyPlansStudyPlanIdProgramMapRoute
}

const StudyPlansStudyPlanIdRouteChildren: StudyPlansStudyPlanIdRouteChildren = {
  StudyPlansStudyPlanIdFrameworkRoute: StudyPlansStudyPlanIdFrameworkRoute,
  StudyPlansStudyPlanIdOverviewRoute: StudyPlansStudyPlanIdOverviewRoute,
  StudyPlansStudyPlanIdProgramMapRoute: StudyPlansStudyPlanIdProgramMapRoute,
}

const StudyPlansStudyPlanIdRouteWithChildren =
  StudyPlansStudyPlanIdRoute._addFileChildren(
    StudyPlansStudyPlanIdRouteChildren,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/study-plans/$studyPlanId': typeof StudyPlansStudyPlanIdRouteWithChildren
  '/programs/$programId/study-plans': typeof ProgramsProgramIdStudyPlansRoute
  '/study-plans/$studyPlanId/framework': typeof StudyPlansStudyPlanIdFrameworkRoute
  '/study-plans/$studyPlanId/overview': typeof StudyPlansStudyPlanIdOverviewRoute
  '/study-plans/$studyPlanId/program-map': typeof StudyPlansStudyPlanIdProgramMapRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/study-plans/$studyPlanId': typeof StudyPlansStudyPlanIdRouteWithChildren
  '/programs/$programId/study-plans': typeof ProgramsProgramIdStudyPlansRoute
  '/study-plans/$studyPlanId/framework': typeof StudyPlansStudyPlanIdFrameworkRoute
  '/study-plans/$studyPlanId/overview': typeof StudyPlansStudyPlanIdOverviewRoute
  '/study-plans/$studyPlanId/program-map': typeof StudyPlansStudyPlanIdProgramMapRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/study-plans/$studyPlanId': typeof StudyPlansStudyPlanIdRouteWithChildren
  '/programs/$programId/study-plans': typeof ProgramsProgramIdStudyPlansRoute
  '/study-plans/$studyPlanId/framework': typeof StudyPlansStudyPlanIdFrameworkRoute
  '/study-plans/$studyPlanId/overview': typeof StudyPlansStudyPlanIdOverviewRoute
  '/study-plans/$studyPlanId/program-map': typeof StudyPlansStudyPlanIdProgramMapRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/study-plans/$studyPlanId'
    | '/programs/$programId/study-plans'
    | '/study-plans/$studyPlanId/framework'
    | '/study-plans/$studyPlanId/overview'
    | '/study-plans/$studyPlanId/program-map'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/study-plans/$studyPlanId'
    | '/programs/$programId/study-plans'
    | '/study-plans/$studyPlanId/framework'
    | '/study-plans/$studyPlanId/overview'
    | '/study-plans/$studyPlanId/program-map'
  id:
    | '__root__'
    | '/'
    | '/study-plans/$studyPlanId'
    | '/programs/$programId/study-plans'
    | '/study-plans/$studyPlanId/framework'
    | '/study-plans/$studyPlanId/overview'
    | '/study-plans/$studyPlanId/program-map'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudyPlansStudyPlanIdRoute: typeof StudyPlansStudyPlanIdRouteWithChildren
  ProgramsProgramIdStudyPlansRoute: typeof ProgramsProgramIdStudyPlansRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudyPlansStudyPlanIdRoute: StudyPlansStudyPlanIdRouteWithChildren,
  ProgramsProgramIdStudyPlansRoute: ProgramsProgramIdStudyPlansRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/study-plans/$studyPlanId",
        "/programs/$programId/study-plans"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/study-plans/$studyPlanId": {
      "filePath": "study-plans.$studyPlanId.tsx",
      "children": [
        "/study-plans/$studyPlanId/framework",
        "/study-plans/$studyPlanId/overview",
        "/study-plans/$studyPlanId/program-map"
      ]
    },
    "/programs/$programId/study-plans": {
      "filePath": "programs.$programId.study-plans.tsx"
    },
    "/study-plans/$studyPlanId/framework": {
      "filePath": "study-plans.$studyPlanId.framework.tsx",
      "parent": "/study-plans/$studyPlanId"
    },
    "/study-plans/$studyPlanId/overview": {
      "filePath": "study-plans.$studyPlanId.overview.tsx",
      "parent": "/study-plans/$studyPlanId"
    },
    "/study-plans/$studyPlanId/program-map": {
      "filePath": "study-plans.$studyPlanId.program-map.tsx",
      "parent": "/study-plans/$studyPlanId"
    }
  }
}
ROUTE_MANIFEST_END */
