/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as StudyPlansStudyPlanIdImport } from './routes/study-plans.$studyPlanId'
import { Route as ProgramsProgramIdStudyPlansImport } from './routes/programs.$programId.study-plans'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StudyPlansStudyPlanIdRoute = StudyPlansStudyPlanIdImport.update({
  id: '/study-plans/$studyPlanId',
  path: '/study-plans/$studyPlanId',
  getParentRoute: () => rootRoute,
} as any)

const ProgramsProgramIdStudyPlansRoute =
  ProgramsProgramIdStudyPlansImport.update({
    id: '/programs/$programId/study-plans',
    path: '/programs/$programId/study-plans',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/study-plans/$studyPlanId': {
      id: '/study-plans/$studyPlanId'
      path: '/study-plans/$studyPlanId'
      fullPath: '/study-plans/$studyPlanId'
      preLoaderRoute: typeof StudyPlansStudyPlanIdImport
      parentRoute: typeof rootRoute
    }
    '/programs/$programId/study-plans': {
      id: '/programs/$programId/study-plans'
      path: '/programs/$programId/study-plans'
      fullPath: '/programs/$programId/study-plans'
      preLoaderRoute: typeof ProgramsProgramIdStudyPlansImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/study-plans/$studyPlanId': typeof StudyPlansStudyPlanIdRoute
  '/programs/$programId/study-plans': typeof ProgramsProgramIdStudyPlansRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/study-plans/$studyPlanId': typeof StudyPlansStudyPlanIdRoute
  '/programs/$programId/study-plans': typeof ProgramsProgramIdStudyPlansRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/study-plans/$studyPlanId': typeof StudyPlansStudyPlanIdRoute
  '/programs/$programId/study-plans': typeof ProgramsProgramIdStudyPlansRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/study-plans/$studyPlanId'
    | '/programs/$programId/study-plans'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/study-plans/$studyPlanId' | '/programs/$programId/study-plans'
  id:
    | '__root__'
    | '/'
    | '/study-plans/$studyPlanId'
    | '/programs/$programId/study-plans'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudyPlansStudyPlanIdRoute: typeof StudyPlansStudyPlanIdRoute
  ProgramsProgramIdStudyPlansRoute: typeof ProgramsProgramIdStudyPlansRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudyPlansStudyPlanIdRoute: StudyPlansStudyPlanIdRoute,
  ProgramsProgramIdStudyPlansRoute: ProgramsProgramIdStudyPlansRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/study-plans/$studyPlanId",
        "/programs/$programId/study-plans"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/study-plans/$studyPlanId": {
      "filePath": "study-plans.$studyPlanId.tsx"
    },
    "/programs/$programId/study-plans": {
      "filePath": "programs.$programId.study-plans.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
