services:
  database:
    image: postgres:16.9-alpine
    environment:
      POSTGRES_DB: flowstruct
      POSTGRES_USER: flowstruct
      POSTGRES_PASSWORD: flowstruct
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pg_data: