name: Deploy Backend - Staging

on:
  push:
    branches:
      - staging
    paths:
      - 'services/backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.BACKEND_DEPLOY_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H ${{ vars.STAGING_VPS_IP }} >> ~/.ssh/known_hosts

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/bake-action@v6
        with:
          source: .
          push: true
          set: |
            *.tags=gjuplans/backend:staging

      - name: Pull backend image
        env:
          VPS_IP: ${{ vars.STAGING_VPS_IP}}
        run: |
          COMPOSE_PATH="services/backend/docker-compose.deploy.yaml"
          CADDYFILE_PATH="services/backend/Caddyfile"
          REMOTE_VPS="admin@$VPS_IP"
          REMOTE_DIR="/opt/gjuplans"
          
          rsync -avz -e "ssh" $COMPOSE_PATH $REMOTE_VPS:$REMOTE_DIR/docker-compose.yaml
          rsync -avz -e "ssh" $CADDYFILE_PATH $REMOTE_VPS:$REMOTE_DIR/Caddyfile
          
          ssh $REMOTE_VPS << EOF
            cd /opt/gjuplans
            sudo docker compose pull
            sudo docker compose up -d
          EOF