name: Deploy API - Staging

on:
  push:
    branches:
      - staging

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy-api.yml
    with:
      image_tag: staging
      vps_ip: ${{ vars.STAGING_VPS_IP }}
    secrets:
      vps_ssh_key: ${{ secrets.VPS_SSH_KEY }}