name: Deploy Backend - Staging

on:
  push:
    branches:
      - staging
    paths:
      - 'services/backend/**'

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy-backend.yml
    with:
      branch: staging
      path: services/backend
      image_tag: staging
      vps_ip: ${{ vars.STAGING_VPS_IP }}
    secrets:
      ssh_key: ${{ secrets.BACKEND_DEPLOY_KEY }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
