name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.BACKEND_DEPLOY_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H api.gjuplans.com >> ~/.ssh/known_hosts

      - name: Build JAR
        run: |
          cd services/backend
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: Deploy JAR to Server
        run: |
          LOCAL_JAR_PATH="services/backend/target/app.jar"
          REMOTE_SERVER="admin@api.gjuplans.com"
          REMOTE_JAR_DIR="/opt/gjuplans"

          rsync -avz -e "ssh" $LOCAL_JAR_PATH $REMOTE_SERVER:$REMOTE_JAR_DIR/app.jar

          ssh $REMOTE_SERVER << EOF
            sudo systemctl restart gjuplans.service
          EOF
