name: Deploy Backend - Production

on:
  push:
    branches:
      - main
    paths:
      - 'services/backend/**'

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy-backend.yml
    with:
      branch: main
      path: services/backend
      image_tag: latest
      vps_ip: ${{ vars.PROD_VPS_IP }}
    secrets:
      ssh_key: ${{ secrets.BACKEND_DEPLOY_KEY }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
