name: Deploy API

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      vps_ip:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H ${{ inputs.vps_ip }} >> ~/.ssh/known_hosts

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/gjuplans-api:${{ inputs.image_tag }}

      - name: Deploy on VPS
        run: |
          REMOTE_VPS="admin@${{ inputs.vps_ip }}"
          REMOTE_DIR="/opt/gjuplans"
          
          rsync -avz -e "ssh" docker-compose.deploy.yaml $REMOTE_VPS:$REMOTE_DIR/docker-compose.yaml
          rsync -avz -e "ssh" Caddyfile $REMOTE_VPS:$REMOTE_DIR/Caddyfile
          
          ssh $REMOTE_VPS << EOF
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          
            cd /opt/gjuplans
            sudo docker compose -f $REMOTE_DIR/docker-compose.yaml pull
            sudo docker compose -f $REMOTE_DIR/docker-compose.yaml up -d
          EOF